### ISSUE TITLE
Rabbit-In-A-Hat files should be XML, not binary

### ISSUE THREAD

**Issue by schuemie** [OHDSI/WhiteRabbit#10]
Currently, ETL specifications are saved as Java binary files. XML would be better because:
- More robust to Java code changes
- Ability to edit the file without Rabbit-In-A-Hat

**Comment by mav7014** [comment]
I'd personally prefer JSON; is there any reason we should stick with XML?

**Comment by mav7014** [comment]
Thanks for accepting my pull request. Do you still intend to support XML in the future or will you close this issue?

**Comment by schuemie** [comment]
Nope, any readable format is fine ;-) Closing this issue now.
