### ISSUE TITLE
SQL error running WhiteRabbit

### ISSUE THREAD

**Issue by malcolmm83** [OHDSI/WhiteRabbit#101]
I'm running WhiteRabbit against a MySQL database, and some of the tables are giving errors.

**\* Generic error information ***
Message: java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
Time: Oct 29, 2015 4:26:47 PM
Processor type: 
Available processors: 8
Maximum available memory: 3,817,865,216 bytes
Used memory: 934,251,304 bytes
Java version: 1.8.0_65
Java vendor: Oracle Corporation
OS architecture: x86_64
OS name: Mac OS X
OS version: 10.10.5
OS patch level: unknown

**\* Stack trace ***
org.ohdsi.databases.RichConnection$DBRowIterator.next(RichConnection.java:468)
org.ohdsi.databases.RichConnection$DBRowIterator.next(RichConnection.java:393)
org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabaseTable(SourceDataScan.java:255)
org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabase(SourceDataScan.java:140)
org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:126)
org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:861)

**\* Console ***
Oct 29, 2015 4:05:23 PM Scanning table AHC_APPT_DATA
Oct 29, 2015 4:05:23 PM Scanning table ALLERGY_REACTION_PROC_ASSO
Oct 29, 2015 4:05:24 PM Scanning table ALL_DB_INFO
Oct 29, 2015 4:05:24 PM Scanning table AUTHENTICATIONTOKENS
Oct 29, 2015 4:05:25 PM Scanning table BOOKS_INFORMATION
Oct 29, 2015 4:05:25 PM Scanning table COSRCOPIA_PATIENT_RESULT
Oct 29, 2015 4:05:26 PM Scanning table COS_ACCOUNT_GUARANTOR_RELN
Oct 29, 2015 4:05:27 PM Scanning table COS_ACCOUNT_INSUR_PLAN_RELN
Oct 29, 2015 4:05:27 PM Scanning table COS_ACCOUNT_RELATIONSHIP
Oct 29, 2015 4:05:28 PM Scanning table COS_ACG_CODES
Oct 29, 2015 4:05:28 PM Scanning table COS_ACH_DETAILS
Oct 29, 2015 4:05:29 PM Scanning table COS_ACTION
Oct 29, 2015 4:05:30 PM Scanning table COS_ACTION_LISTENER
Oct 29, 2015 4:05:30 PM Scanning table COS_ACTIVITY_GRAPH
Oct 29, 2015 4:05:34 PM Scanning table COS_ACTIVITY_MED_TEMPLATE
Oct 29, 2015 4:05:37 PM Scanning table COS_ACTIVITY_MISC_TEMPLATE
Oct 29, 2015 4:05:38 PM Scanning table COS_ACTIVITY_ORDER_TEMPLATE
Oct 29, 2015 4:05:39 PM Scanning table COS_ACTIVITY_PROCEDURE
Oct 29, 2015 4:05:40 PM Scanning table COS_ACTIVITY_ROLE_DEFN
Oct 29, 2015 4:05:44 PM Scanning table COS_ACTIVITY_SYSTEM_TEMPLATE
Oct 29, 2015 4:05:45 PM Scanning table COS_ACTIVITY_TEMPLATE
Oct 29, 2015 4:05:51 PM Scanning table COS_ACTIVITY_TEMPLATE_ATTRIB
Oct 29, 2015 4:05:59 PM Scanning table COS_ADDRESS
Stopped after 100000 rows
Oct 29, 2015 4:07:31 PM Scanning table COS_ADDRESS_MAP
Oct 29, 2015 4:07:32 PM Scanning table COS_ADG_CODES
Oct 29, 2015 4:07:33 PM Scanning table COS_ADVERSE_CATEGORY
Oct 29, 2015 4:07:33 PM Scanning table COS_ADVERSE_EVENT
Oct 29, 2015 4:07:34 PM Scanning table COS_ADVERSE_EVENT_GRADE
Oct 29, 2015 4:07:38 PM Scanning table COS_ADV_DIRECTIVE_PARTICIPANT
Oct 29, 2015 4:07:40 PM Scanning table COS_AGENT_ROUTE
Oct 29, 2015 4:07:40 PM Scanning table COS_ALERT
Oct 29, 2015 4:07:52 PM Scanning table COS_ALERTS_DEFINED
Oct 29, 2015 4:07:53 PM Scanning table COS_ALERTS_DEFINED_ACTIONS
Oct 29, 2015 4:07:53 PM Scanning table COS_ALERT_ACTION
Oct 29, 2015 4:07:54 PM Scanning table COS_ALERT_ACTION_PARMS
Oct 29, 2015 4:07:55 PM Scanning table COS_ALERT_COMPANY
Oct 29, 2015 4:07:56 PM Scanning table COS_ALERT_DETAIL_PAGE
Oct 29, 2015 4:07:57 PM Scanning table COS_ALERT_DETECTION_SCHEDULE
Oct 29, 2015 4:07:58 PM Scanning table COS_ALERT_NOTIFICATION
Oct 29, 2015 4:07:59 PM Scanning table COS_ALERT_RESOLUTION
Oct 29, 2015 4:08:01 PM Scanning table COS_ALERT_ROLE
Stopped after 100000 rows
Oct 29, 2015 4:09:55 PM Scanning table COS_ALERT_ROLE_ACTION
Stopped after 100000 rows
Oct 29, 2015 4:10:57 PM Scanning table COS_ALERT_RUN
Oct 29, 2015 4:10:58 PM Scanning table COS_ALERT_RUN_SUMMARY
Oct 29, 2015 4:10:59 PM Scanning table COS_ALERT_STATUS
Oct 29, 2015 4:11:06 PM Scanning table COS_ALERT_TEMPLATE
Oct 29, 2015 4:11:07 PM Scanning table COS_ALERT_TEMPLATE_ACTION
Oct 29, 2015 4:11:08 PM Scanning table COS_ALERT_TEMPLATE_PARMS
Oct 29, 2015 4:11:08 PM Scanning table COS_ALERT_USER
Oct 29, 2015 4:11:09 PM Scanning table COS_ALLERGY
Oct 29, 2015 4:11:10 PM Scanning table COS_ALLERGY_CONCERN_ACT_ASSO
Oct 29, 2015 4:11:11 PM Scanning table COS_ALLERGY_GROUP
Oct 29, 2015 4:11:12 PM Scanning table COS_ALLERGY_REACTION_MED_ASSO
Oct 29, 2015 4:11:12 PM Scanning table COS_ALLERGY_REA_SEV_ASSO
Oct 29, 2015 4:11:13 PM Scanning table COS_ALLERGY_SEV_ASSO
Oct 29, 2015 4:11:13 PM Scanning table COS_ANSWER
Oct 29, 2015 4:11:14 PM Scanning table COS_ANSWER_TYPE
Oct 29, 2015 4:11:15 PM Scanning table COS_APC
Oct 29, 2015 4:11:15 PM Scanning table COS_APPLICATION_IDENTIFIER
Oct 29, 2015 4:11:16 PM Scanning table COS_APPOINTMENT
Oct 29, 2015 4:11:16 PM Scanning table COS_ASN
Oct 29, 2015 4:11:18 PM Scanning table COS_ASN_LN
Oct 29, 2015 4:11:20 PM Scanning table COS_ASN_LOT
Oct 29, 2015 4:11:22 PM Scanning table COS_ATTR_METADATA
Oct 29, 2015 4:11:35 PM Scanning table COS_ATTR_METADATA1
Oct 29, 2015 4:11:38 PM Scanning table COS_AUDITABLE_INFO
Oct 29, 2015 4:11:38 PM Scanning table COS_AUDIT_TRAIL
Oct 29, 2015 4:11:39 PM Scanning table COS_AUDIT_UPLOAD
Oct 29, 2015 4:11:40 PM Scanning table COS_AUTH_REQUEST
Oct 29, 2015 4:11:42 PM Scanning table COS_AUTH_REQUEST_DIAG
Oct 29, 2015 4:11:43 PM Scanning table COS_AUTH_REQUEST_PROC
Oct 29, 2015 4:11:44 PM Scanning table COS_BANK_DETAILS
Oct 29, 2015 4:11:45 PM Scanning table COS_BASE_SPECIMEN
Oct 29, 2015 4:11:46 PM Scanning table COS_BILLING
Oct 29, 2015 4:11:59 PM Scanning table COS_BILLING_DIAGNOSIS
Oct 29, 2015 4:12:00 PM Scanning table COS_BILLING_HDR_COLLECTION
Oct 29, 2015 4:12:01 PM Scanning table COS_BILLING_HDR_COLL_COMMENT
Oct 29, 2015 4:12:02 PM Scanning table COS_BILLING_HDR_ITEM
Oct 29, 2015 4:12:04 PM Scanning table COS_BILLING_HDR_SERVICE_TYPE
Oct 29, 2015 4:12:06 PM Scanning table COS_BILLING_HEADER
Oct 29, 2015 4:12:12 PM Scanning table COS_BILLING_HEADER_HISTORY
Oct 29, 2015 4:12:17 PM Scanning table COS_BILLING_ITEM_TRANSACTION
Oct 29, 2015 4:13:36 PM Scanning table COS_BILL_EVENT
Oct 29, 2015 4:13:38 PM Scanning table COS_BOOK
Oct 29, 2015 4:13:38 PM Scanning table COS_BP_PRTCL_DATA
Oct 29, 2015 4:13:39 PM Scanning table COS_BP_PRTCL_PRMTR
Oct 29, 2015 4:13:41 PM Scanning table COS_BRM_CATEGORY
Oct 29, 2015 4:13:42 PM Scanning table COS_BRM_CATEGORY_ASSOC
Oct 29, 2015 4:13:43 PM Scanning table COS_BRM_CRITERIA
Oct 29, 2015 4:13:43 PM Scanning table COS_BRM_FACTS
Oct 29, 2015 4:13:44 PM Scanning table COS_BRM_FACT_ALIAS
Oct 29, 2015 4:13:44 PM Scanning table COS_BRM_FACT_ENTITY
Oct 29, 2015 4:13:45 PM Scanning table COS_BRM_FACT_METHOD
Oct 29, 2015 4:13:45 PM Scanning table COS_BRM_FACT_METHOD_PARAMS
Oct 29, 2015 4:13:46 PM Scanning table COS_BRM_PARAM_VALUE
Oct 29, 2015 4:13:46 PM Scanning table COS_BRM_RULE
Oct 29, 2015 4:13:47 PM Scanning table COS_BRM_RULESET
Oct 29, 2015 4:13:48 PM Scanning table COS_BRM_RULE_REACTIVE_TRIGGER
Oct 29, 2015 4:13:49 PM Scanning table COS_BRM_RULE_SCHED_TRIGGER
Oct 29, 2015 4:13:49 PM Scanning table COS_BRM_RULE_TRIGGER
Oct 29, 2015 4:13:50 PM Scanning table COS_CALENDAR_ASSOC
Oct 29, 2015 4:13:51 PM Scanning table COS_CALENDAR_BLOCK
Oct 29, 2015 4:13:52 PM Scanning table COS_CALENDAR_DAY
Oct 29, 2015 4:13:52 PM Scanning table COS_CALENDAR_TEMPLATE
Oct 29, 2015 4:13:53 PM Scanning table COS_CAMPAIGN
Oct 29, 2015 4:13:54 PM Scanning table COS_CAMPAIGN_ACTIVITY_DEFN
Oct 29, 2015 4:13:56 PM Scanning table COS_CAMPAIGN_ENRLLMNT_EXCPTN
Oct 29, 2015 4:13:57 PM Scanning table COS_CANCER_CODE_VALUE
Oct 29, 2015 4:13:58 PM Scanning table COS_CANCER_HISTOLOGY_CODE_VAL
Oct 29, 2015 4:13:58 PM Scanning table COS_CANCER_MORPHOLOGY_CODE_VAL
Oct 29, 2015 4:13:59 PM Scanning table COS_CANCER_TOPOGRAPHY_CODE_VAL
Oct 29, 2015 4:14:00 PM Scanning table COS_CARE_PLAN
Oct 29, 2015 4:14:04 PM Scanning table COS_CARE_PLAN_ACTION
Oct 29, 2015 4:14:04 PM Scanning table COS_CARE_PLAN_FORM
Oct 29, 2015 4:14:05 PM Scanning table COS_CARE_PLAN_MEASURE
Oct 29, 2015 4:14:07 PM Scanning table COS_CARE_PLAN_MEASURE_FREQ
Oct 29, 2015 4:14:10 PM Scanning table COS_CARE_PLAN_MEASURE_GOAL
Oct 29, 2015 4:14:11 PM Scanning table COS_CARE_PLAN_MEASURE_GRAPH
Oct 29, 2015 4:14:12 PM Scanning table COS_CARE_PLAN_RULE_EVENT_ASSOC
Oct 29, 2015 4:14:14 PM Scanning table COS_CARE_PLAN_TRTMT
Oct 29, 2015 4:14:16 PM Scanning table COS_CASE
Oct 29, 2015 4:14:17 PM Scanning table COS_CCD
Oct 29, 2015 4:14:17 PM Scanning table COS_CCDA_HEADER
Oct 29, 2015 4:14:19 PM Scanning table COS_CCD_DOCUMENT
Oct 29, 2015 4:14:19 PM Scanning table COS_CHARGE_MASTER
Oct 29, 2015 4:14:28 PM Scanning table COS_CHRONIC_CONDITION
Oct 29, 2015 4:14:29 PM Scanning table COS_CLAIM
Oct 29, 2015 4:14:30 PM Scanning table COS_CLAIM_ADJ_DENIAL_RSN_CD
Oct 29, 2015 4:14:32 PM Scanning table COS_CLAIM_DIAGNOSIS
Oct 29, 2015 4:14:32 PM Scanning table COS_CLAIM_DIAGNOSIS_NEW
Oct 29, 2015 4:14:34 PM Scanning table COS_CLAIM_EVENT_METADATA
Oct 29, 2015 4:14:56 PM Scanning table COS_CLAIM_EVENT_METADATA_ARC
Oct 29, 2015 4:15:03 PM Scanning table COS_CLAIM_ITEM
Oct 29, 2015 4:15:04 PM Scanning table COS_CLAIM_ITEM_ADJ_SEG
Oct 29, 2015 4:15:05 PM Scanning table COS_CLAIM_ITEM_AGING
Oct 29, 2015 4:15:06 PM Scanning table COS_CLAIM_ITEM_CONTRIBUTION
Oct 29, 2015 4:15:07 PM Scanning table COS_CLAIM_ITEM_MODIFIER
Oct 29, 2015 4:15:07 PM Scanning table COS_CLAIM_ITEM_PAYMENT
Oct 29, 2015 4:15:08 PM Scanning table COS_CLAIM_ITEM_POOL_DIST
Oct 29, 2015 4:15:09 PM Scanning table COS_CLAIM_ITEM_PROVIDER_DIST
Oct 29, 2015 4:15:10 PM Scanning table COS_CLAIM_PAYMENT
Oct 29, 2015 4:15:11 PM Scanning table COS_CLAIM_PAYMENT_LINK
Oct 29, 2015 4:15:12 PM Scanning table COS_CLAIM_PMT_HDR
Oct 29, 2015 4:15:18 PM Scanning table COS_CLAIM_PMT_HDR_ADJ
Oct 29, 2015 4:15:19 PM Scanning table COS_CLAIM_PMT_HDR_REMARK
Oct 29, 2015 4:15:30 PM Scanning table COS_CLAIM_PMT_LINE
Oct 29, 2015 4:15:33 PM Scanning table COS_CLAIM_PMT_LINE_ADJ
Oct 29, 2015 4:15:35 PM Scanning table COS_CLAIM_PMT_LINE_REMARK
Oct 29, 2015 4:15:35 PM Scanning table COS_CLAIM_PMT_PROV_ADJ
Oct 29, 2015 4:15:36 PM Scanning table COS_CLAIM_STATUS
Oct 29, 2015 4:15:36 PM Scanning table COS_CLAIM_SUBMISSION
Oct 29, 2015 4:15:38 PM Scanning table COS_CLINICALNOTE_SEC_CMNTS
Oct 29, 2015 4:15:39 PM Scanning table COS_CLINICALSTUDY_GROUP
Oct 29, 2015 4:15:40 PM Scanning table COS_CLINICALSTUDY_PATIENT
Oct 29, 2015 4:15:42 PM Scanning table COS_CLINICAL_NOTE
Oct 29, 2015 4:15:44 PM Scanning table COS_CLINICAL_STUDY
Oct 29, 2015 4:15:46 PM Scanning table COS_CLM_CLAIM
Oct 29, 2015 4:20:32 PM Scanning table COS_CLM_CLAIM_ADDTNL_INFO1
Oct 29, 2015 4:22:22 PM Scanning table COS_CLM_CLAIM_ADDTNL_INFO2
Oct 29, 2015 4:23:17 PM Scanning table COS_CLM_CLAIM_ADDTNL_PRV
Stopped after 100000 rows
Oct 29, 2015 4:24:48 PM Scanning table COS_CLM_CLAIM_ADJUSTMENT
Oct 29, 2015 4:24:49 PM Scanning table COS_CLM_CLAIM_DIAGNOSIS
Stopped after 100000 rows
Oct 29, 2015 4:25:30 PM Scanning table COS_CLM_CLAIM_INST_PRCDR
Oct 29, 2015 4:25:49 PM Scanning table COS_CLM_CLAIM_ITEM
Oct 29, 2015 4:26:29 PM Scanning table COS_CLM_CLAIM_REPRICING
Oct 29, 2015 4:26:30 PM Scanning table COS_CLM_ITEM_TOP_DENIAL_RESONS
Oct 29, 2015 4:26:31 PM Scanning table COS_CODED_ENTITIES
Oct 29, 2015 4:26:37 PM Scanning table COS_CODE_HL7_CODE_MAP
Oct 29, 2015 4:26:37 PM Scanning table COS_CODE_TYPE
Oct 29, 2015 4:26:38 PM Scanning table COS_CODE_VALUE
Oct 29, 2015 4:26:42 PM Scanning table COS_CODE_VALUE_BK
Oct 29, 2015 4:26:43 PM Scanning table COS_CODE_VALUE_COMPANY
java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1084)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
    at com.mysql.jdbc.ResultSetImpl.getTimestampFromString(ResultSetImpl.java:6293)
    at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5867)
    at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5688)
    at org.ohdsi.databases.RichConnection$DBRowIterator.next(RichConnection.java:453)
    at org.ohdsi.databases.RichConnection$DBRowIterator.next(RichConnection.java:393)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabaseTable(SourceDataScan.java:255)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabase(SourceDataScan.java:140)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:126)
    at org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:861)
Error: java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp

**\* Working folder contents ***
Directory of /Users/malcolmmcroberts/OHDSI/WhiteRabbit

WhiteRabbit and Rabbit-In-a-Hat User Manual.pdf                          951,058                   22-08-2014 02:54:22
WhiteRabbit.jar                                                          306,695                   12-10-2015 10:54:58
RabbitInAHat.jar                                                         598,626                   12-10-2015 10:55:00
WhiteRabbit_lib                                                              612      <DIR>        12-10-2015 10:58:38
Error.txt                                                                  8,192                   29-10-2015 04:26:47

Available disc space: 67,273,240,576 bytes

**Comment by schuemie** [comment]
This seems to be a problem with the JDBC driver and zero date-time values (see [here](http://stackoverflow.com/questions/11133759/0000-00-00-000000-can-not-be-represented-as-java-sql-timestamp-error) for details). I implemented the solution of adding something to the connection URL. I also updated the JDBC driver to the latest version just in case.

I do not have MySQL installed (WhiteRabbit is the only OHDSI tool that supports MySQL, all other tools require PostgreSQL, SQL Server or Oracle). Could you test out the [new version](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.5.5)? The problem seems to be in the COS_CODE_VALUE_COMPANY table, so you may want to start your test there.

**Comment by malcolmm83** [comment]
I'm testing with the new Jar now.  Thanks for the quick response. I'll let
you know how it goes.
