### ISSUE TITLE
White rabbit v5.3 to v5.4 issues executing

### ISSUE THREAD

**Issue by rband** [OHDSI/WhiteRabbit#102]
I have both versions of whiterabbit on my desktop.  But when I try to execute (either rabbitinahat or whiterabbit) of ver5.3 nothing happens! v5.4 works fine. Anyone else see this. 5.3 used to work for me before. Also on v5.4 I am unable to change the CDM version. Selecting CDMv4 does nothing. If anyone else has seen this problem before, any help would be appreciated. Thanks/

**Comment by schuemie** [comment]
Not sure why version 5.3 is no longer working, but I did find the bug that prevent you from switching to CDM v4. Please get the [latest release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.5.6).

Please note that CDM v4 is quickly being phased out in OHDSI. Existing tools might have v4 support, but new tools will only support v5. It is highly recommended you use CDM v5.
