### ISSUE TITLE
SQL Server tables in non-dbo schema

### ISSUE THREAD

**Issue by dawazualex** [OHDSI/WhiteRabbit#108]
When running a scan, the add button brings up a list of schema-less tables, but when you try to scan a table not in the default schema, it throws an 'invalid object' error

**Comment by prashanrampersad** [comment]
Hello

What is the expected timeline for resolution of this issue ?

I see it still exists in Version 0.77. Not being able to specify a Schema for the scan makes the tool unusable for schema-specified databases. The alternative currently is to re-organise the source database.

Thanks
Prashan

**Comment by schuemie** [comment]
Give me until tomorrow. I think I have it figured out, but need to run some tests.

**Comment by schuemie** [comment]
Could you give [this new release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.7.8) a try?

**Comment by prashanrampersad** [comment]
Hi

Thanks for the quick response. Version 0.78 works well for schema differentiated SQL Server databases. Good effort.

Regards
Prashan

**Comment by schuemie** [comment]
Thanks!
