### ISSUE TITLE
Table Name Length

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#113]
Need to do some error handling around table name length.  

If you don't limit table names to 31 characters you end up with some issues.  MS Excel only displays 31 characters in the tab name.  If the name of the table ends up being longer than 31, Rabbit In a Hat cannot connect the table name to the tab with the data in it.

For Example, when scanning the Synpuf CSVs:
- Original File Name: `DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_1`
- File Name Scanned: `2008_to_2010_Prescription_Drug_Events_1`
- Tab Name: `2008_to_2010_Prescription_Drug_`

**Comment by ericaVoss** [comment]
You can trim .CSV out of the names by default.

**Comment by schuemie** [comment]
Appears related to [this issue](https://github.com/OHDSI/WhiteRabbit/issues/14).

**Comment by MaximMoinat** [comment]
Fixed through PR #162. Trimming of file extension is deliberately not implemented as this can cause additional table name conflicts.
