### ISSUE TITLE
Command Line Support

### ISSUE THREAD

**Issue by panCtrlV** [OHDSI/WhiteRabbit#114]
Can I run WhiteRabbit from command line instead of using GUI. I found scanning my database takes long time. I want to run it in background and let it generate reports.

**Comment by schuemie** [comment]
Currently not, but I can see that would be a useful feature that is easy to add. Give me a couple of days to implement...

**Comment by panCtrlV** [comment]
Thank you.

**Comment by schuemie** [comment]
Hi @panCtrlV,

I think everything should work now. Could you give it a try? Make sure you download the [latest release](https://github.com/OHDSI/WhiteRabbit/releases/tag/0.5.17), then see the instructions [here](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:whiterabbit#running_from_the_command_line).

**Comment by panCtrlV** [comment]
@schuemie 

In the .ini file, I changed the following two lines

SERVER_LOCATION = 127.0.0.1/data_base_name
DATABASE_NAME = schema_name

Other than that, the command line tool works swimmingly. 👍 

Thank you very much.

**Comment by schuemie** [comment]
Ah, good point! I updated the example ini file accordingly.

Thanks!
