### ISSUE TITLE
Testing Framework - lookup_* functions bug

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WhiteRabbit#115]
When using the testing framework, there is a bug in the lookup_* R functions which generates invalid SQL. Here is an example:

lookup_person("person_id", person_source_value = "12-34") results in the following SQL:

SELECT person_id FROM @cdmsource.person WHERE person_source_value 'AND 12-34 AND'.

**Comment by schuemie** [comment]
Thanks! I've created a [new release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.5.18) incorporating your fix.
