### ISSUE TITLE
Adding support for Google BigQuery

### ISSUE THREAD

**Issue by mgkahn** [OHDSI/WhiteRabbit#117]
I've been given instructions for how to connect to Google BigQuery via a newly released JDBC driver (instructions attached here). I'd like to try this driver with WhiteRabbit but  can't figure out how I can manipulate the fields in the WR configuration screen to make this work. Is it possible?

[Simba_JDBC.pdf](https://github.com/OHDSI/WhiteRabbit/files/609562/Simba_JDBC.pdf)

**Comment by schuemie** [comment]
It isn't just a matter of pointing WhiteRabbit to the JDBC driver. The driver will need to be added to the application, and some additional code will need to be added to tell WhiteRabbit how to do certain things in the BigQuery dialect (e.g. how to select a random set of rows from a table).

Recently someone added support for Microsoft Access, which should give you an idea of the changes that are required. See these commits:
a0fd8c027087d5c104fe05819b08baf476be36ab
49d90f7a191b0e2da804d7d66772812779562cea
7b6c3a642ec344065f4e92a04ebb46e3b5641f1c
e41763a00a96cc2d8ca6bd98e9b41a814d9eedcf

**Comment by mgkahn** [comment]
Just pointing to Pull Request (Issue #173) which includes a number of small code changes (and additional jars) to enable BigQuery support. Not sure who needs to be notified of the PR or how the PR gets communicated to the project team (PRs are new to me).

**Comment by mgkahn** [comment]
I'm wondering what I can go to get this work either rejected or incorporated into the main branch. We've been using this version in Colorado w/o issues.

**Comment by MaximMoinat** [comment]
Sorry for the delay (and the lack of love), but I have finally tested and merged your PR! 

Thanks for the nudge :), your contribution is much, much, appreciated.

**Comment by mgkahn** [comment]
After a bit of delay, I added documentation to the WR wiki for connecting to GBQ data sources via both user default authentication and service accounts. I believe this issue can now be closed until some bug or enhancement comes up in the future. OK to close?

**Comment by MaximMoinat** [comment]
Thanks. And just in time, planning to publish the new release v0.9.0 (with your GBQ integration) next week at the latest. Closing this issue now.
