### ISSUE TITLE
Testing Framework - nested lookup functions

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WhiteRabbit#118]
In some recent ETL testing, I needed to perform nested lookups. My use case was that I needed to have a lookup function (lookup_visit_occurrence) use another lookup function (lookup_person). I was able to accomplish this by adding a check for the "subQuery" class in my local version of the testing framework. I think this would be useful to add for all lookup_* functions in the framework. 

Currently the pattern in the lookup_<entity> functions is:
```

  if (!missing(<column_name_param>)) {
    if (is.null(<column_name_param>)) {
      whereClauses <- c(whereClauses, "<column_name> IS NULL")
    } else {
      whereClauses <- c(whereClauses, paste0("<column_name> = '", <column_name_param>,"'"))
    }
  }

```
where <column_name> is the table column name and <column_name_param> is the value supplied to the lookup function. The new pattern to handle nested lookup functions should be:

```
  if (!missing(<column_name_param>)) {
    if (is.null(<column_name_param>)) {
      whereClauses <- c(whereClauses, "<column_name> IS NULL")
    } else if (is(<column_name_param>, "subQuery")){
      whereClauses <- c(whereClauses, paste0("<column_name> = (", as.character(<column_name_param>), ")"))
    } else {
      whereClauses <- c(whereClauses, paste0("<column_name> = '", <column_name_param>,"'"))
    }
  }
```

**Comment by schuemie** [comment]
Should be fixed in this commit  c135d9ddb7bf1e9fef85a2d7c61a8a7637b69e38
