### ISSUE TITLE
Fake data in Delimited Text Files

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WhiteRabbit#120]
I am aware that the fake data generation is experimental, but it is pretty useful and I found a quite obvious bug. Namely: the "Delimiter" option doesn't have any affect on the format. The only option is hard coded to a standard CSV export (RFC4180).

A simple fix is to rename the Data Type to "CSV Files" and disable the Delimiter option.

A better fix is to make multiple formats available. [The CSVFormat documentation](https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html) mentions four predefined formatting options:
- [x] RFC4180
- [x] DEFAULT
- [x] EXCEL
- [x] MYSQL
- [x] TDF

I tweaked the code already to facilitate TDF (was needed for a simple bulk insert), so I could implement the others properly in the near future. 
Therefore I would like to know: are there already more ideas/efforts on improving the fake data feature? And are there other desired text formats?

**Comment by schuemie** [comment]
Hi @MaximMoinat ,

As far as I know you're the only one currently using this feature. I have no plans to work on it.

If you want to take a stab at implementing support for those other formats that would be greatly appreciated!
