### ISSUE TITLE
Testing Framework- List of test cases

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#124]
It would be nice to have a way to export a list of test cases to excel, possibly by leveraging the declareTest function in the testing framework from RiaH.

**Comment by tropicalberto** [comment]
that would be really useful. I usually do this adding a few extra lines at the end of the main script, to export the results from the unit tests:

`# View the results and write them
querySql(connection, 'SELECT * FROM test_results')
write.table(querySql(connection, 'SELECT * FROM test_results'), "unittest_results.csv",sep=",",row.names=FALSE )
`

It would be also really handy to add an option to export only the test results that failed.

By the way. Is there any reason why when you don't expect a value in an OMOP table (e.g. expect_no_condition_occurrence(....) then if the unit test is succesful, the result is "Expect condition_occurrence". That's a bit confusing.

**Comment by MaximMoinat** [comment]
Looking into this issue and thinking to export a table like the following:

testId|testDescription|testType|tableTested
---|---|---|---
1|Drop patients with no gender|expect no|person
2|Patient with strange birth date|expect|person
3|Observation period takes earliest start and latest stop|expect|person
3|Observation period takes earliest start and latest stop|expect|observation_period

@clairblacketer, would the following address your use case? Any other test details you need? (e.g. expected fields and values - which does make the export a lot more complex)
