### ISSUE TITLE
[STEM] Cause of Death

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#126]
DEATH shouldn't be attached to STEM.

**REASON 1**
There is not one CONCEPT with a DOMAIN_ID = 'Death'

**REASON 2**
We mapped STEM.CONCEPT_ID to DEATH.CAUSE_CONCEPT_ID.  Clair and I don't think this is right anymore.  I think we need to add a CAUSE_CONCEPT_ID to the STEM, because the CONCEPT_ID that gets you to a DEATH is not the cause it is just be an indicator.

https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/rabbitInAHat/dataModel/StemTableDefaultMappingV5.0.1.csv#L91

**REASON 3**
Additionally DEATH_TYPE_CONCEPT_ID probably shouldn't be set from TYPE_CONCEPT_ID.  For DEATH we forget provenance and say how death was assigned. 

@schuemie if you agree we can update the CSV.

**Comment by schuemie** [comment]
Yep, sounds good to me!

**Comment by clairblacketer** [comment]
In the latest release the STEM -> DEATH mapping is no longer there
