### ISSUE TITLE
[STEM] ID 

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#127]
Fix missing IDs
http://forums.ohdsi.org/t/id-in-rabbit-in-a-hat-stem/2883

**Comment by schuemie** [comment]
Your changes are incorporated in [the latest release](https://github.com/OHDSI/WhiteRabbit/releases). Please let me know if it works.

**Comment by clairblacketer** [comment]
I just checked it and all looks good!
