### ISSUE TITLE
LOOKUP in declareTest()

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#130]
I'd like to be able to use the LOOKUP_PERSON() function in the declareTest() function so that I can populate the test results table with what the CDM.PERSON_ID is.

I see right now the LOOKUP_PERSON() function provides the SQL to find the CDM.PERSON_ID however declareTest() is just expecting a value in CDM_PID not to execute a statement.

**Comment by schuemie** [comment]
I'm not sure I understand the problem. The LOOKUP functions are intended to be used inside EXPECT statements, like [this](https://github.com/OHDSI/ETL-CDMBuilder/blob/master/man/JMDC/TEST_CASES/JmdcTests.R#L34).

**Comment by clairblacketer** [comment]
I understand what @ericaVoss is saying because you get an error if you use LOOKUP_PERSON() in declareTest() to set cdm_pid. I got around this by adding parentheses around the lookup like this:

`declareTest("Patient has diagnosis_code = 25000 and diagnosis_qual = 1", source_pid = paste(patient$hvid,"16",sep = "-"), cdm_pid = paste0("(",personLookup,")"))`

**Comment by ericaVoss** [comment]
@schuemie - I understand that the LOOKUP_FUNCTION just writes a SQL function but is there an easy way to resolve it outside a EXPECT statement?  Basically like @clairblacketer says above, we'd like to use it in the declareTest().  Even if we could resolve it outside declareTest() and then just set it to a variable that is fine too.  Reason why is in a builder where PERSON_SOURCE_VALUE != PERSON_ID looking up the IDs is annoying for testing.

**Comment by schuemie** [comment]
I'm not sure I'm following. The `declareTest` just creates a human-readable label to group tests. Why does it have to have a person_id?

**Comment by ericaVoss** [comment]
So when you have a failed test you can look at the CDM data and the RAW data together to see where the builder messed up (or in my case, where I wrote a crappy test case).
