### ISSUE TITLE
STEM table for CDM v5.1.0

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#134]
In the most recent release of RabbitInAHat I get an error that the stem table is not available for CDM v5.1.0

**Comment by schuemie** [comment]
Ah yes, a STEM table definition (see [this example](https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/rabbitInAHat/dataModel/StemTableV5.0.1.csv)) and STEM table default mapping (see [this example](https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/rabbitInAHat/dataModel/StemTableDefaultMappingV5.0.1.csv)) need to be created for CDM v5.1.0.

Any volunteers? @ericaVoss?

In fact, we'll also need to add v5.2.0.

**Comment by clairblacketer** [comment]
Created PR #135 adding these documents for CDM 5.1.0 and CDM v5.2.0
