### ISSUE TITLE
For oracle if the sample size is greater than row count, the query is null and cause a null exception in the result set

### ISSUE THREAD

**Issue by 18818569575** [OHDSI/WhiteRabbit#138]
https://github.com/OHDSI/WhiteRabbit/blob/ec4b3507d61b5d87a863056be56998484a2d21f3/src/org/ohdsi/whiteRabbit/scan/SourceDataScan.java#L300

**Comment by schuemie** [comment]
Sorry about that! This should be fixed in the new release: https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.7.1

Could you give it a try?

**Comment by 18818569575** [comment]
I have tested this release on my Oracle 11g and it is ok.

**Comment by schuemie** [comment]
Thanks!
