### ISSUE TITLE
For blob column type in oracle getString will cause an exception

### ISSUE THREAD

**Issue by 18818569575** [OHDSI/WhiteRabbit#139]
https://github.com/OHDSI/WhiteRabbit/blob/ec4b3507d61b5d87a863056be56998484a2d21f3/src/org/ohdsi/databases/RichConnection.java#L496

**Comment by schuemie** [comment]
I don't have a good environment to test this, so I just surrounded the whole statement with a try catch block: https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/databases/RichConnection.java#L498

This is also incorporated in the new release: https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.7.1

Could you give it a try?

**Comment by schuemie** [comment]
I'm not very familiar with Oracle (as you may already have guessed). Why did you choose to restrict to GBK encoding? Are there other types of encoding we could consider adding?

WhiteRabbit is designed to handle free text fields, and it seems that BLOB is the only option in Oracle to store free text, so I would prefer to handle BLOBs elegantly.

**Comment by 18818569575** [comment]
I am not either. Maybe it needs someone more sophisticated to handle all the encodings of the blob type. I just work it out in my case.

**Comment by 18818569575** [comment]
I have tested this release on my Oracle 11g and it is ok.

**Comment by schuemie** [comment]
Thanks! 

I'll just leave it as is until someone asks for this feature.
