### ISSUE TITLE
Files with matching first 31 characters causes error 

### ISSUE THREAD

**Issue by wistephens** [OHDSI/WhiteRabbit#14]
Excel Sheet names can be 31 characters at most. When processing files with long matching prefixes, as happens with TCGA data, I receive the following error: 

"Error: The workbook already contains a sheet of this name"

Example files that cause failures: 
https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/anonymous/tumor/brca/bcr/biotab/clin/

**Comment by JohnDomar** [comment]
I found the issue , the table name is truncated to make the sheet name, two of my tables had the same name , except for the characters at the end,so all I did was slightly rename one , re ran the analysis and its worked.
