### ISSUE TITLE
If the order of fields is different in the fieldInfos variable and the row variable, the value may be put into wrong field

### ISSUE THREAD

**Issue by 18818569575** [OHDSI/WhiteRabbit#140]
https://github.com/OHDSI/WhiteRabbit/blob/4b998a5231526af0f27f1a5d7f993316366b7c24/src/org/ohdsi/whiteRabbit/scan/SourceDataScan.java#L263

**Comment by schuemie** [comment]
One solution would be to turn `fieldInfos` into a Map from field name to FieldInfo, and do the `get` using the name. Should be easy to fix.

Just so we don't do the same work twice: shall I do that?

**Comment by 18818569575** [comment]
My fork is restricted to process GBK encoding blob type, but it may provide one way to fix it.
https://github.com/18818569575/WhiteRabbit/commit/bea365af31e99df21d5718df63be1dd61f1ea34d

**Comment by schuemie** [comment]
Thanks! That is actually a more elegant solution. I'll just copy your code.

Do expect to be filing more issues in the short term?

**Comment by 18818569575** [comment]
Currently, we are working on adopting OHDSI, we have part of our database analyzed with this tool successfully, but maybe more issues will be encountered and I will try to report and work out some solutions.

**Comment by schuemie** [comment]
Ok, in that case I'll wait a bit before creating another release.
