### ISSUE TITLE
Automatically grab new CDM definition from GitHub

### ISSUE THREAD

**Issue by schuemie** [OHDSI/WhiteRabbit#141]
As updates to the CDM become more common, it might be a good idea to write a process that simply grabs the current definition from the [CDM Github repo](https://github.com/OHDSI/CommonDataModel/tree/master/Documentation/CommonDataModel_Wiki_Files).

**Comment by MaximMoinat** [comment]
Hello Martijn, we have been looking for something like that as well. In the end we have written a simple python notebook that reads the CDM wiki files and creates the RiaH csv files: 
https://github.com/thehyve/OHDSI-CommonDataModel/tree/create-riah-csv/Documentation/CommonDataModel_csv_create 

Did you envision something like this?

**Comment by schuemie** [comment]
Hi @MaximMoinat ,

Yes, that is exactly what I mean! 

However, it seems we should be able to write something that goes directly from the source (whatever the source is), so I'll investigate that first: https://github.com/OHDSI/CommonDataModel/issues/135

**Comment by schuemie** [comment]
A CSV version of the CDM is now part of the standard output in the CommonDataModel repo: https://github.com/OHDSI/CommonDataModel/issues/89

You can plug that CSV file into RiaH.
