### ISSUE TITLE
Rabbit in hat jar gives NullPointerException

### ISSUE THREAD

**Issue by rssurdikar** [OHDSI/WhiteRabbit#143]
Hi,

 I downloaded latest [white rabbit jar](https://github.com/OHDSI/WhiteRabbit/tree/v0.7.2) which supports CDM v5.2.0 tables. But faced with null pointer exception as shown in following screen shot.

![rabbitinhat_error](https://user-images.githubusercontent.com/26762226/32894607-45cb2580-cb03-11e7-90af-2413e5bde1db.png)

After debugging, I found there is bug in source code 
https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/rabbitInAHat/dataModel/Database.java

```
public enum CDMVersion {
		CDMV4("CDMV4.csv"), CDMV5("CDMV5.csv"), 
                CDMV501("CDMV5.0.1.csv"), CDMV510("CDMV5.1.0.csv"), 
                CDMV520("CDMV5.2.0.csv");

		private final String	fileName;

		CDMVersion(String fileName) {
			this.fileName = fileName;
		}
	} 
```
Actual file name is: https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/rabbitInAHat/dataModel/CDMv5.2.0.csv

Either Need to rename this file from **CDMv5.2.0.csv** to **CDMV5.2.0.csv** or update CDMVersion enum to fix this bug.

For now, I just updated file name in jar and it's working fine.

**Comment by schuemie** [comment]
Thanks! 

Would you mind testing this [new release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.7.3) and see if the problem is now solved?

**Comment by rssurdikar** [comment]
Yes. It's solved. We can close this issue now.

**Comment by schuemie** [comment]
Thanks!
