### ISSUE TITLE
DDL Generation

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#144]
If we are scanning the DB would it be possible to generate an OHDSQL DDL of the raw data?  This could help when executing the test cases but you lack a set up native version of the raw data.

**Comment by schuemie** [comment]
For now you could probably use the fake data generator in WhiteRabbit to achieve this (set max rows to 0 if you only want the structure). 

Note that the data types might not be exactly the same (e.g. BIGINT probably became INT).
