### ISSUE TITLE
Detect native variables that start with an underscore

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#145]
If the native database has a column that begins with an underscore, R throws an error when trying to source TestingFramework.R because R naming conventions do not allow you to start a name with an underscore.

**Comment by MaximMoinat** [comment]
This should be fixed in the meantime (see replacement below done for all names used). Please reopen if it still occurs.

https://github.com/OHDSI/WhiteRabbit/blob/6b9a2b1305df3a70995bc4811930ee323d610e6b/rabbitinahat/src/main/java/org/ohdsi/rabbitInAHat/ETLTestFrameWorkGenerator.java#L379-L382
