### ISSUE TITLE
get('testNewAdded') throws error without environment specified

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#146]
In each of the add_* functions that are created in the framework it looks for an object called 'testNewAdded' and returns the value using the `get()` function. This throws an error because it does not know where to look for the object. I added `envir=frameworkContext` to the call and it fixed the problem.

The same thing happens with the 'testNewExpected' object

**Comment by schuemie** [comment]
I'm not able to reproduce the error. Could you be more specific in the steps needed to encounter this error?

Are you using `Generate ETL Test Framework` or `Generate ETL Test Framework (for R packages)`?

**Comment by clairblacketer** [comment]
I am using `Generate ETL Test Framework (for R packages)` for the Cerner database. I then source the resulting file and run `initFramework()`. Then, when I try to run `add_hf_d_patient()` to create a test case, that is when I get the error. I will email you the scan report I used to generate the framework if that helps.

**Comment by clairblacketer** [comment]
I just generated the framework using `Generate ETL Test Framework` and it worked much better. I just sourced the file upon loading the package and I don't get the error.
