### ISSUE TITLE
OJDBC--the problem of incompatible

### ISSUE THREAD

**Issue by Yovoss** [OHDSI/WhiteRabbit#149]
when connecting to Oracle, there are console message about "Exception in thread "AWT-EventQueue-0" java.lang.Error: Incompatible version of libocijdbc[Jdbc:122010, Jdbc-OCI:121020", so is it the incompatible of the version of ojdbc?

**Comment by schuemie** [comment]
Oracle doesn't provide the most informative error messages. It seems like the JDBC driver and your local ODAC are of incompatible versions. 

I've updated the Oracle driver. Could you give [this new release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.7.6) a try?

**Comment by schuemie** [comment]
Hi @Yovoss : could you confirm whether the update fixed the problem?

**Comment by chPark5667** [comment]
I also have same problem. 
I  try build  v0.7.6 code  to eclipse.
 Our Evironment is 12c oracle.

**Comment by chPark5667** [comment]
I solved this problem.
First of all you should check your oracle DBMS version.
In my case 12.2.0.1.0 version which is for enterprise.
So I did download my DBMS version's ojdbc8 .
 
In this way I could solve this problem.
