### ISSUE TITLE
Consider sorting columns alphabetically in RabbitInAHat

### ISSUE THREAD

**Issue by wistephens** [OHDSI/WhiteRabbit#15]
When attempting to map input columns to CDM columns, neither attribute list is sorted. This leaves the user to scan the lists to find the fields of interest. With small column lists this is not a big issue, but when attempting to process > ~ 15 columns it requires scrolling and dragging columns.  

Consider sorting column names alphabetically to make searching easier.

**Comment by aguynamedryan** [comment]
We made a little movie showing off how this feature works.  Tables can now be filtered by name.  Type in any part of a name and all matching tables will be displayed.  Type in a pipe character to "or" your search criteria together.  

The filters also work when viewing fields.

![filtering](https://cloud.githubusercontent.com/assets/117722/7945812/f362ef66-0927-11e5-9faa-df4957b49046.gif)
