### ISSUE TITLE
Issue running on 32-bit JVM

### ISSUE THREAD

**Issue by prashanrampersad** [OHDSI/WhiteRabbit#151]
Hello

I am a new user of WhiteRabbit. Downloaded the latest version and followed the instructions. Double clicking on WhiteRabbit.jar does nothing. Executing from the command line gives the following:

![image](https://user-images.githubusercontent.com/35492256/53079820-2ee37f00-34ef-11e9-8d57-fcccf123a115.png)

Any ideas on what I may be doing wrong ?

Thanks
Prashan

**Comment by prashanrampersad** [comment]
On a 64-Bit Windows Machine, you will need to have 64-Bit Java. It will not work with 32-Bit

**Comment by schuemie** [comment]
Thanks for letting us know!

I don't know why it didn't run on 32-bits, but it would be nice if you'd have gotten a more informative error message

**Comment by schuemie** [comment]
Closing for now. Can be reopened when this issue appears again
