### ISSUE TITLE
Use public jars for building

### ISSUE THREAD

**Issue by blootsvoets** [OHDSI/WhiteRabbit#152]
For auditing and security purposes, it would be good to know the origin and current security status of the libraries listed in the `lib` folder. This would be easier to automate if the build would use Maven or Gradle for dependency resolution, since then there are standard security scanners like dependabot or Snyk.io to verify the current dependency status.

Dependencies that are not available via standard Maven repositories like Maven Central or JCenter could still be listed in this directory and referenced directly.

**Comment by schuemie** [comment]
I agree. We tend to use Maven for other OHDSI projects. I think all these dependencies are available through Maven.

Would this be something you would be willing to contribute?

**Comment by blootsvoets** [comment]
In principle, yes. I'm not sure about a timeline though, it may be months rather than weeks.

**Comment by schuemie** [comment]
In master now. Thanks!
