### ISSUE TITLE
Comments not in markdown file

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#157]
When using the comment function in Rabbit in a hat, they do not come across in the final markdown document. I use this function by mapping a source table to a cdm table, clicking on the arrow to get into the mapping/logic screen. To put a comment on a cdm field I click on the field rather than drawing an arrow to it. These comments persist in the program even if I map multiple source tables to one cdm table, however they do not show up in the rendered markdown file.

**Comment by schuemie** [comment]
This was a bug. Could you try [the new version](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.8.1)?
