### ISSUE TITLE
More detail for connecting to redshift

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/WhiteRabbit#158]
I attempted to use WhiteRabbit v0.8.0 to connect to redshift using the same server location I used with prior versions of the tool. The prior version will connect but I get the following request from the current version : 

![image](https://user-images.githubusercontent.com/12911960/59118106-5be06400-891d-11e9-8f8b-3c86729f4b2b.png)

Can there be some description added to the wiki about how to connect to redshift using the newest version?

**Comment by schuemie** [comment]
This was a bug in the latest release. Could you try [the new one](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.8.1)?
