### ISSUE TITLE
Error writing report after scanning database

### ISSUE THREAD

**Issue by JohnDomar** [OHDSI/WhiteRabbit#161]
Database scans but then errors when trying to write the report
"...
Generating scan report
Error: The workbook already contains a sheet of this name.. "
Despite specifying a new (empty) directory
removing error logs etc

**Comment by JohnDomar** [comment]
Update - seems to be one specific database that causes this error - its quite large, should that affect it ?

**Comment by qubitina** [comment]
Seems to be the same problem in #14.

**Comment by MaximMoinat** [comment]
Hi @JohnDomar. This is indeed a known issue and happens if table names in a database are very long (WR truncates to 31 characters), as mentioned in the linked issue. We are working on a fix.
