### ISSUE TITLE
Add OMOP concept_id hints in RiaH

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WhiteRabbit#163]
For RiaH it would be useful to have hints for concepts, e.g. gender_concept_id can only have two values; 8507 (MALE) and 8531 (FEMALE). Similar for all the type_concept_ids. During the mapping process one would always need to look these up, so it would save effort if the user is presented with the options in the RiaH interface.

@clairblacketer Do you have a list of fields that are associated with certain (domain of) concepts?

**Comment by PRijnbeek** [comment]
Yes, I like this. You need to find a way to keep this updated of course, can be in releases since these things do not change often.

It may be useful to make these link to ATHENA so you can see them in context as we have implemented in Tantalus (only useful if you can have internet connection during ETL).

**Comment by MaximMoinat** [comment]
A first mock to illustrate the general idea, also shown during the OHDSI ETL tutorial. The UI needs to be updated
![image](https://user-images.githubusercontent.com/17825660/64926904-71451400-d7d1-11e9-8495-a4d1a3ff8afd.png)

**Comment by schuemie** [comment]
Excellent idea! I think @clairblacketer and @pbr6cornell have developed the structured data that allows to infer valid concepts per field as part of the Data Quality Dashboard that could be re-used here.

**Comment by AEW0330** [comment]
This is very cool and very useful! Would those structured data also allow other RiaH-DQD synergies described here?: https://github.com/OHDSI/WhiteRabbit/issues/180

**Comment by MaximMoinat** [comment]
@AEW0330 The primary purpose for RiaH is to document mappings, not to check them for validity. Currently, there is no standardised way in RiaH to enter your mappings to concept_ids, it is all free text.
We are thinking about warnings when certain required fields are not filled by the user, so to check completeness.

**Comment by MaximMoinat** [comment]
> It may be useful to make these link to ATHENA so you can see them in context as we have implemented in Tantalus (only useful if you can have internet connection during ETL).

That would have been a nice feature. But as it is really easy to search for a concept_id in Athena or Atlas, we choose to keep RiaH simple and don't link it to Athena itself.
