### ISSUE TITLE
Ingest a source data dictionary in RiaH

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WhiteRabbit#164]
Together with the source scan report, RiaH should be able to also ingest a source data dictionary (in a predefined format) with description of tables and fields. In this way, RiaH contains all the information of the source data needed for defining mapping rules.

**Comment by PRijnbeek** [comment]
Identical to #168?

**Comment by MaximMoinat** [comment]
Ah, yes, I will close this one.
