### ISSUE TITLE
Scan Report exploration in RiaH

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WhiteRabbit#169]
Following the WR scope discussions in #166 and #167, this merges these requests by focussing on using RiaH for source data exploration. Currently the excel scan report is often used for this, but RiaH is actually better suited for **navigation** through tables and columns, although not usable as such at the moment.
 
While RiaH displays the details from the scan report when defining the mapping rules, it does not support simply clicking through source tables to explore the fields in the data. A mapping to a target table has to be defined first.

An added benefit of using RiaH for source data exploration is that you can report any findings in directly in RiaH comments, which would be displayed during the mapping phase as well.

Some practical improvements:
- [x] Enter the column view by double clicking the table name.
- [x] Add an 'exploration mode', which hides target tables
- [ ] Import the source data dictionary, see also ~#164~ #168
- [ ] Advanced; plot frequency distributions
- [ ] Advanced; plot histogram for numerical data #165 

@marcel1334 and @PRijnbeek @clairblacketer Very interested in what you think of such an 'exploration mode' in RiaH. From your experience, would people use RiaH in this way?

**Comment by marcel1334** [comment]
"Source Data Exploration": this term perfectly covers what I was aiming for in the feature requests.

When doing an ETL for an UNKNOWN source database this exploration is a first step. I also saw the the excel sheet was used for this and wished it contained a bit more info about the tables and columns. Designing an ETL is the combination of source data exploration and mapping it to the CDM. Integrating some simple stats this in the ETL design tool itself would be great.

Again, not the goal to make a full featured source data profiler. Lets keep is simple.

**Comment by MaximMoinat** [comment]
Basic exploration feature implemented in version 0.10.0
