### ISSUE TITLE
Not able to find the file whiteRabbit.bat when the whiteRabbit-master.zip downloaded from github 

### ISSUE THREAD

**Issue by abhishekverma2601** [OHDSI/WhiteRabbit#172]
I am not able to find the file bin/whiteRabbit.bat  when the whiteRabbit-master.zip downloaded from github .So not able to install the whiteRabbit .
Can you please tell me if i am missing something ?
Zip file for whiterab
[WhiteRabbit-master.zip](https://github.com/OHDSI/WhiteRabbit/files/3559956/WhiteRabbit-master.zip)
bit is attached .

-Abhishek

**Comment by don-torok** [comment]
In the Readme it says 
Getting Started

WhiteRabbit

    Under the Releases tab, download WhiteRabbit*.zip
    Unzip the download
    Double-click on bin/whiteRabbit.bat on Windows to start White Rabbit, and bin/whiteRabbit on macOS and Linux.

Is that where you got the zip file from?  To me it looks like the file name would be WhiteRabbit_v0.8.0.zip

**Comment by abhishekverma2601** [comment]
Thanks Don , i tried downloading the  file name WhiteRabbit_v0.8.0.zip as well but did not find the bin/whiteRabbit.bat file  in the downloaded folder .Any idea why it is missing ?Any workaround ? thanks .

**Comment by don-torok** [comment]
Try unzipping WhiteRabbit_v0.8.0.zip and then in Windows just double-click on WhiteRabbit.jar. This will work if you have files with the .jar extension associated with Java.

**Comment by abhishekverma2601** [comment]
Thanks , i downloaded the WhiteRabbit_v0.8.0.zip  but didnot find the file WhiteRabbit.jar in downloaded folder . Is *.java compilation required .Sorry i am not a developer so asking this basic question .

**Comment by don-torok** [comment]
No jar file is the compiled file.  Just try double clicking the jar file to
see if it runs.

**Comment by abhishekverma2601** [comment]
Thanks for update , i did not find the jar file after extracting the zip WhiteRabbit_v0.8.0.zip  .

**Comment by don-torok** [comment]
Ok. but in the bin directory do you see whiteRabbit.bat?  Because I see it in my download

**Comment by abhishekverma2601** [comment]
Got it now , thank you .I was downloading from the left side icon so these files were missing .

**Comment by MaximMoinat** [comment]
Closing this thread, as it seems to be resolved.
