### ISSUE TITLE
Using WhiteRabbit to generate fake data

### ISSUE THREAD

**Issue by toanong** [OHDSI/WhiteRabbit#18]
Hi,

I used White Rabbit to scan OMOP V4 tables and then used the data profiles to generate fake data. However, only several tables (care_site, location, organization, oscar_result, provider) were included in the output. Was the limitation the result of this being an experimental function or me using OMOP V4 tables?

Thank you in advance.

**Comment by schuemie** [comment]
This feature is experimental, but there should be no reason why it wouldn't work when applied to a database in CDM format. Could you tell me what DBMS (Postgres? Oracle?) you're using? Are you using the same DBMS for holding the source (CDM) data and the target (fake) data?
