### ISSUE TITLE
Issue while connecting the whiterabbit fto the mysql database 

### ISSUE THREAD

**Issue by abhishekverma2601** [OHDSI/WhiteRabbit#182]
Getting the below error while connecting to MySQL server from whiterabbit . All details given are correct "could not connect : Cannot connect to DB server : Could not create connection to database serv . Please let me know if I am missing some thing .
[error.docx](https://github.com/OHDSI/WhiteRabbit/files/3639412/error.docx)
er "

**Comment by MaximMoinat** [comment]
Closing this as it is a duplicate. Will follow-up in the other thread.
