### ISSUE TITLE
Table names in orange box

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/WhiteRabbit#186]
In a session we see this:

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/7252105/65695389-5dba6880-e06f-11e9-84f6-ac87baaac293.png">

Especially strange the double table names.

**Comment by MaximMoinat** [comment]
This looks like a rendering issue. Was it only affecting these two boxes, or did other boxes also show this issue while scrolling through the pane? 

Also I see that the line breaks are not great with these long table names, creating unnecessary text out of bounds.
