### ISSUE TITLE
[Rabbit In a Hat] Warning Needed when Opening Files

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#19]
If you pick the wrong file (e.g. you try to open the ETL file as a scan report) Rabbit in a Hat just hangs.  It might be nice for it to give a user warning that the file type choosen is inappropriate.

Also, I would switch the order of the menu items, you need to open the SCAN REPORT before you have an ETL.  There is a logical order there.

These are both cosmetic items.

**Comment by aguynamedryan** [comment]
Closed by #85
