### ISSUE TITLE
DEATH table missing in CDM 6.0 mappings

### ISSUE THREAD

**Issue by rsurdikar** [OHDSI/WhiteRabbit#196]
Downloaded [latest](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.8.2) white rabbit release on windows machine and was working on CDM 6.0 mappings for my data-set and observed that it's missing `Death` table. 

Can we please add it back?

Seems like it was there in [previous](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.7.9) CDM 5.3.1 version.

**Comment by MaximMoinat** [comment]
The death table is deprecated in v6, see https://github.com/OHDSI/CommonDataModel/wiki/death
So either use v5.3.1 or a custom target schema.
