### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#202]
User guide and Help: WhiteRabbit Wiki
https://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:whiterabbit

We should plan to retire this for the Book of OHDSI and then anything not in the Book of OHDSI should be in GitHub (e.g. the connection strings).

**Comment by MaximMoinat** [comment]
As commented in the other thread, I am thinking of migrating the documentation to Github Pages. See also  https://forums.ohdsi.org/t/documentation-for-white-rabbit-white-rabbit-new-release/9068. 

Not sure what you meant with the comment regarding the Book of OHDSI. Do you say we should also keep the ohdsi wiki page such that the BoO references still work? Or only document here what is not documented in the BoO?
