### ISSUE TITLE
Central Repository no longer supports insecure communication over plain HTTP

### ISSUE THREAD

**Issue by YaroslavTir** [OHDSI/WhiteRabbit#206]
I noticed that you are using an http url link for maven central. That 
```
		<repository>
			<id>central</id>
			<name>Central Repository</name>
			<url>http://repo.maven.apache.org/maven2/ </url>
		</repository>
```
it can lead to the `Return code is: 501 , ReasonPhrase:HTTPS Required`  
https://stackoverflow.com/a/59764670/1167673

Maven already has proper maven repository by default. So I would just suggest to remove the lines from the pom. 
Related https://github.com/OHDSI/ArachneCommons/issues/225

**Comment by blootsvoets** [comment]
It looks like this is already fixed.
