### ISSUE TITLE
Missing Column from CDM v6.0

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#211]
In RabbitInAHat, we were trying to map DISCHARGE_TO - "The source code for the discharge disposition as it appears in the source data."

I think these columns are missing in RabbitInaHat to map to:
STEM.DISCHARGE_TO_CONCEPT_ID
STEM.DISCHARGE_TO_SOURCE_VALUE
VISIT_DETAIL.DISCHARGE_TO_CONCEPT_ID
VISIT_DETAIL.DISCHARGE_TO_SOURCE_VALUE

But let me know if we got it wrong.

**Comment by MaximMoinat** [comment]
The visit detail discharge columns are to added in PR #210. There were more issues with the v6 model added in RiaH. 

I just asked for your review. Could you check it out?

Regarding the stem table, the `visit_occurrence` and `visit_detail` are not targets for the stem table, only the 'event' tables are. So adding the discharge fields to the stem table should not be necessary. Or am I missing something?

**Comment by MaximMoinat** [comment]
Fixed by #210. Thanks for reviewing (and merging)!
