### ISSUE TITLE
WhiteRabbit v0.9.0 Unable to Launch

### ISSUE THREAD

**Issue by MikeHamidi** [OHDSI/WhiteRabbit#220]
After downloading v.0.9.0, I could not launch WhiteRabbit. However, no issue launching RabbitInAHat. By reverting back to WhiteRabbit v0.8.0, I did not have any issues launching either app. No error logs were reported and all corresponding setup instructions were followed. See OS and Java details below.

- Windows 10 Pro
-- Version 1809
-- OS Build 17763.1098
- Java v8 updated 251 (build 1.9.0_251-b08)

**Comment by clairblacketer** [comment]
I am having this same issue with v0.10.0

**Comment by MaximMoinat** [comment]
Something we have seen on Windows, is an issue with the working folder. A solution in that case was moving the application folder (`dist`) to the root drive (e.g. to C:\).

Could you try whether that works for you?

**Comment by sebastiaan101** [comment]
I have the same issue: White Rabbit v0.10.0 and now v.0.10.1 do not launch, no problem with Rabbit in a Hat. 
Windows 10 Pro version 1909.
Did try moving the `dist` folder, to no avail. Do you have another suggestion?

**Comment by sebastiaan101** [comment]
@MaximMoinat I checked earlier versions: WR v0.8.0 and v0.8.2 do start up in Windows10. WR v0.9.0 does not.

**Comment by MaximMoinat** [comment]
The issue could be due to 32-bit vs 64-bit systems. There might have been updates for v0.9.0 that restrict WR on 64-bit.

@clairblacketer @sebastiaan101 @MikeHamidi 
To confirm this hypothesis, could you check whether your Java or Windows is 32 or 64 bit?

**Comment by sebastiaan101** [comment]
In my case, both Windows and Java are fully 64-bit...

Sebastiaan van Sandijk
informatters +company
s.vansandijk@informatters.nl
+31 6 526 24 582


Op ma 27 jul. 2020 10:39 schreef Maxim Moinat <notifications@github.com>:

**Comment by sebastiaan101** [comment]
@MaximMoinat I played around with another tool, and found a way to get WR working: I edited whiterabbit.bat, changing the JAVA options to `%JAVACMD% %JAVA_OPTS% -Xmx1200m ...` (instead of -Xmx2400m). i guess it does the same as what you wanted to accomplish with the JVM arg setting, but this worked.

**Comment by MaximMoinat** [comment]
Great, that helps a lot. We will change this setting

**Comment by MaximMoinat** [comment]
This should be fixed with the new release, v0.10.2

@sebastiaan101 @clairblacketer @MikeHamidi Please let me know if it works now.

**Comment by MikeHamidi** [comment]
This seems to be fixed now on my end. I'm now running under C:\ w/out any issues. As a side note, I originally had it under OneDrive and ran into issues.
