### ISSUE TITLE
percentage appears >99% in all cases

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/WhiteRabbit#239]
![image](https://user-images.githubusercontent.com/6586384/84522215-39a5c280-aca4-11ea-80e5-2058a7d3d9f7.png)

![image](https://user-images.githubusercontent.com/6586384/84522298-580bbe00-aca4-11ea-8b80-85583390ffed.png)

**Comment by MaximMoinat** [comment]
Hi Frank, this should now be fixed in v0.10.1 #220 
Please download the latest version and re-import your scan report.

**Comment by MaximMoinat** [comment]
@fdefalco Can you confirm that this solved your issue?
