### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#24]
Prior to 1a7aa9397f7c290eb2e0ccc07d2e6e11002c4352, I wasn't able to build this project by running "ant" from the command line.  After 1a7aa9397f7c290eb2e0ccc07d2e6e11002c4352, I'm still unable to build the project, but I'm getting a couple of new errors I'd like to throw your way.

First, the ``<fileset dir="bin"/>`` lines are causing the build to fail with the message ``WhiteRabbit/bin does not exist.``

If I manually make the ``bin`` dir and rerun the ant command, the build seems to complete, but when I cd in to the ``dist`` directory and run
```
sh RabbitInAHat1.5GB.sh 
Error: Could not find or load main class org.ohdsi.rabbitInAHat.RabbitInAHatMain
```
and with WhiteRabbit, the same
```
sh WhiteRabbit1.5GB.sh
Error: Could not find or load main class org.ohdsi.whiteRabbit.WhiteRabbitMain
```

As soon as I'm able to build this project, I'll be able to test a few changes I've made to RabbitInAHat in relation to #21

**Comment by schuemie** [comment]
Hmmm,  the problem seems to be that the Ant script doesn't compile,  but instead assumes the compiled code is already in the bin folder. 

I won't be able to fix it in the next few days. For now,  you can try adding it to the Ant script yourself,  or compile into bin.

**Comment by schuemie** [comment]
The Ant build wasn't including the icons and CSV files. They're now being added directly to the JAR. Let me know if this works for you.

**Comment by aguynamedryan** [comment]
I'm able to build and run both WhiteRabbit and RabbitInAHat.  I think this one is OK to close.

**Comment by schuemie** [comment]
Thanks!
