### ISSUE TITLE
Scan List To Filter Tables in DB

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#271]
When you have a LARGE database (600+ tables), it would be good if there was a way to import a list of the table names you would like to select.  This would save time when you do another scan.

**Comment by MaximMoinat** [comment]
This can be done by running WR from the command line and storing the tables names in the `TABLES_TO_SCAN ` property of the `.ini` file.
 
http://ohdsi.github.io/WhiteRabbit/WhiteRabbit.html#running_from_the_command_line
