### ISSUE TITLE
Problem when saving the ETL with Rabbit-In-a-Hat

### ISSUE THREAD

**Issue by songotho** [OHDSI/WhiteRabbit#278]
![708005F1-1E3F-42DC-ADD4-74C4674CD177](https://user-images.githubusercontent.com/391476/95734153-b75ef680-0cb5-11eb-9b92-39ce23ea69dd.jpg)
When I try to save the ETL, the software is dumped.
I can't do anything afterward.

Plz, help to cross-check it if it's possible.
I downloaded the version of the software here: https://github.com/OHDSI/WhiteRabbit
My scan file is around 58Mb.

Thanks.

**Comment by songotho** [comment]
![0C59BD24-9A0C-4D22-A2F0-DACE4A67F870](https://user-images.githubusercontent.com/391476/95735462-694af280-0cb7-11eb-83eb-fa78107bbd61.jpeg)

Here is the error that shows.

**Comment by MaximMoinat** [comment]
@songotho I see you closed the issue. Could you comment whether you have indeed solved the problem and how you solved it? Could be helpful for future reference.

**Comment by songotho** [comment]
> @songotho I see you closed the issue. Could you comment whether you have indeed solved the problem and how you solved it? Could be helpful for future reference.

Hi Max, 
I try to solve it by ourselves, two possible ways could be: 1. Increasing the memory of JVM by using -Xmx[size_of_ram] (but it did not work for us as I tried putting 16Gb). 2. Reducing the loading scan file (Trying now).
Regards,
Alex.
