### ISSUE TITLE
VISIT_DETAIL in CDMv5.3.1

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#279]
Is VISIT_DETAIL_ID missing from STEM in CDMv5.3.1?

Tagging @clairblacketer

**Comment by ericaVoss** [comment]
Also, is MODIFIER_SOURCE_VALUE in there twice?

**Comment by MaximMoinat** [comment]
I think you found two bugs indeed. Should be simple to resolve in the following two csv files. And we should also check the other relevant cdm versions for these issues.

https://github.com/OHDSI/WhiteRabbit/blob/master/rabbitinahat/src/main/resources/org/ohdsi/rabbitInAHat/dataModel/StemTableV5.3.1.csv
https://github.com/OHDSI/WhiteRabbit/blob/master/rabbitinahat/src/main/resources/org/ohdsi/rabbitInAHat/dataModel/StemTableDefaultMappingV5.3.1.csv

**Comment by MaximMoinat** [comment]
@ericaVoss And feel free to open a PR 😄. Please use `dev` as target branch.
