### ISSUE TITLE
[Suggested Feature] Overall Notes Section

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WhiteRabbit#28]
It would be good if there was a place to put a "header note" or just general notes.  For example, if you need to do pre-processing before you start the ETL (e.g. pivot SEER data so you can actually deal with it) or you just have notes you need to stick SOMEWHERE (e.g. notes on something you need to do)

The results of this text box could just spit out to the top of the document.

**Comment by aguynamedryan** [comment]
@ericaVoss, while #90 isn't an "overall notes" section, it will allow you to add notes to right below the header of any table.  Hopefully that will meet your needs.  If not, feel free to reopen this issue.
