### ISSUE TITLE
Crashing RiaH: Hard coded path to jni.cpp

### ISSUE THREAD

**Issue by canuckianM6P** [OHDSI/WhiteRabbit#282]
Moving this from Developer forum to this project.  

Hello. OHDSI newbie here. Really enjoying the deep toolsets and community effort.

The question is with the Rabbit In A Hat (WhiteRabbit_v0.10.2)

I have a scan in hand from the White Rabbit, application from the Sample 1 Claims set for SynPuf data.

When I run the RIAH.bat, it starts, I am using the CDM v6 as the target schema, which opens by default.

As soon as I select the “Open Scan File” item from the File menu or use the keyboard shortcut RIAH closes (crashes). I do not get to a point where I can select a file, the whole app closes. A log is written and is, in part below.

I’ve attempted the following with the same result:

A confirmed version of Java at least 1.8

With the default memory allocation as well as bumping it up to 4096m.

Running the batch file as regular or administrator.

My environment is Winx64, Java 1.8

Log shows:

Start----

JRE version: Java™ SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
Java VM: Java HotSpot™ 64-Bit Server VM (25.101-b13 mixed mode windows-amd64 compressed oops)
Problematic frame:
C [msvcr100.dll+0x36adf]
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.
<<>>

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1874 sun.awt.shell.Win32ShellFolder2.getDisplayNameOf(JJI)Ljava/lang/String; (0 bytes) @ 0x00000000036dc489 [0x00000000036dc440+0x49]
j sun.awt.shell.Win32ShellFolder2.access$1600(JJI)Ljava/lang/String;+4
j sun.awt.shell.Win32ShellFolder2$13.call()Ljava/lang/String;+15
j sun.awt.shell.Win32ShellFolder2$13.call()Ljava/lang/Object;+1
J 1909 C1 java.util.concurrent.FutureTask.run()V (126 bytes) @ 0x00000000036f00d4 [0x00000000036efe80+0x254]
j java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run()V+7
j java.lang.Thread.run()V+11
v ~StubRoutines::call_stub
----End

Probing questions or suggestions would be appreciated.

Thank you!

SECOND POST:

Looking closer at the error log reveals a crash due to a file not found a reference to jni.cpp. The expected path is not referenced in the batch file and so far looks like a reference within the code. Details for the error are below.

Start Error—
Internal exceptions (10 events):
Event: 0.085 Thread 0x0000000002ff7000 Exception <a ‘java/security/PrivilegedActionException’> (0x000000076ab9cf20) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.129 Thread 0x0000000002ff7000 Exception <a ‘java/security/PrivilegedActionException’> (0x000000076ad69d08) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.129 Thread 0x0000000002ff7000 Exception <a ‘java/security/PrivilegedActionException’> (0x000000076ad69f18) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.130 Thread 0x0000000002ff7000 Exception <a ‘java/security/PrivilegedActionException’> (0x000000076ad6c478) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.130 Thread 0x0000000002ff7000 Exception <a ‘java/security/PrivilegedActionException’> (0x000000076ad6c688) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.134 Thread 0x0000000002ff7000 Exception <a ‘java/io/FileNotFoundException’> (0x000000076ad76260) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.165 Thread 0x0000000002ff7000 Exception <a ‘java/lang/NoSuchFieldError’: method resolution failed> (0x000000076ae43968) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.166 Thread 0x0000000002ff7000 Exception <a ‘java/lang/NoSuchFieldError’: method resolution failed> (0x000000076ae50d38) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.220 Thread 0x0000000002ff7000 Exception <a ‘java/io/FileNotFoundException’> (0x000000076af01da8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u101\7261\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.491 Thread 0x0000000002ff7000 Implicit null exception at 0x0000000003331559 to 0x0000000003331d9b

Noob question, is this intended to run outside of the in-a-box solution?

Thanks!

**Comment by canuckianM6P** [comment]
Issue resolved by pointing my local JAVA_HOME to a newer JDK, in my case Open JDK 15.0.2.

**Comment by MaximMoinat** [comment]
Great that you have figured this out. And many thanks for reporting your solution!
