### ISSUE TITLE
Priority WhiteRabbit bug

### ISSUE THREAD

**Issue by komalrawal1991** [OHDSI/WhiteRabbit#283]
After download nor White rabbit and Rabbit in Hat not working:

![image](https://user-images.githubusercontent.com/76897970/107246150-f4fe4100-6a55-11eb-8523-ce8b2edd675a.png)

**Comment by MaximMoinat** [comment]
It seems like Windows is set to be very protective, and doesn't allow any applications it does not know. In general this is very good as you have to know what you are doing if running uncertified open source software like WhiteRabbit.

So if you trust WhiteRabbit, you have to somehow tell Windows as well to trust the application and run it. Typically you can find these settings in the Control Panel under Security settings.

**Comment by w0ut0** [comment]
Related to #287

**Comment by MaximMoinat** [comment]
@komalrawal1991 The simple solution is to press 'More info' and then a button 'Run Anyway' will appear. Make sure you trust the software before you do that (all source code is available here, you can also build the binaries yourself).
