### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.apache.poi:poi-ooxml-schemas

### ISSUE THREAD

**Issue by Bing-ok** [OHDSI/WhiteRabbit#288]
## Issue description:
There are multiple versions of **_org.apache.poi:poi-ooxml-schemas_** in **_rabbit-core_**. As shown in the following dependency tree, according to Maven's "nearest wins" strategy, only **_org.apache.poi:poi-ooxml-schemas:3.9_** can be loaded, **_org.apache.poi:poi-ooxml-schemas:3.17_** will be shadowed.

However, several methods defined in shadowed version **_org.apache.poi:poi-ooxml-schemas:3.17_** are referenced by client project via **_org.apache.poi:poi-ooxml:3.17_** but missing in the actually loaded version **_org.apache.poi:poi-ooxml-schemas:3.9_**.

For instance, the following missing method(defined in **_org.apache.poi:poi-ooxml-schemas:3.17_**) are actually referenced by **_rabbit-core_**, which will introduce a runtime error(i.e., "NoSuchMethodError") into **_rabbit-core_**.

1. **_com.microsoft.schemas.office.visio.x2012.main.MasterContentsDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.MasterContentsDocument parse(java.io.InputStream)_** is invoked by **_rabbit-core_** via the following path:
<pre><code>
Invocation path------
&lt;org.ohdsi.ooxml.CustomXWPFDocument: void init(java.io.InputStream)&gt; WhiteRabbit\rabbit-core\target\classes
&lt;org.apache.poi.xwpf.usermodel.XWPFDocument: void init(java.io.InputStream)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.POIXMLDocument: void load(org.apache.poi.POIXMLFactory)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XmlVisioDocument: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XDGFMasters: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XDGFMasterContents: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;com.microsoft.schemas.office.visio.x2012.main.MasterContentsDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.MasterContentsDocument parse(java.io.InputStream)&gt;
</code></pre>

2. **_com.microsoft.schemas.office.visio.x2012.main.MastersDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.MastersDocument parse(java.io.InputStream)_** is invoked by **_rabbit-core_** via the following path:
<pre><code>
Invocation path------
&lt;org.ohdsi.ooxml.CustomXWPFDocument: void init(java.io.InputStream)&gt; WhiteRabbit\rabbit-core\target\classes
&lt;org.apache.poi.xwpf.usermodel.XWPFDocument: void init(java.io.InputStream)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.POIXMLDocument: void load(org.apache.poi.POIXMLFactory)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XmlVisioDocument: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XDGFMasters: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;com.microsoft.schemas.office.visio.x2012.main.MastersDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.MastersDocument parse(java.io.InputStream)&gt;
</code></pre>

3. **_com.microsoft.schemas.office.visio.x2012.main.PageContentsDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.PageContentsDocument parse(java.io.InputStream)_** is invoked by **_rabbit-core_** via the following path:
<pre><code>
Invocation path------
&lt;org.ohdsi.ooxml.CustomXWPFDocument: void init(java.io.InputStream)&gt; WhiteRabbit\rabbit-core\target\classes
&lt;org.apache.poi.xwpf.usermodel.XWPFDocument: void init(java.io.InputStream)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.POIXMLDocument: void load(org.apache.poi.POIXMLFactory)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XmlVisioDocument: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XDGFPages: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XDGFPageContents: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;com.microsoft.schemas.office.visio.x2012.main.PageContentsDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.PageContentsDocument parse(java.io.InputStream)&gt;
</code></pre>

4. **_com.microsoft.schemas.office.visio.x2012.main.PagesDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.PagesDocument parse(java.io.InputStream)_** is invoked by **_rabbit-core_** via the following path:
<pre><code>
Invocation path------
&lt;org.ohdsi.ooxml.CustomXWPFDocument: void init(java.io.InputStream)&gt; WhiteRabbit\rabbit-core\target\classes
&lt;org.apache.poi.xwpf.usermodel.XWPFDocument: void init(java.io.InputStream)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.POIXMLDocument: void load(org.apache.poi.POIXMLFactory)&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XmlVisioDocument: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;org.apache.poi.xdgf.usermodel.XDGFPages: void onDocumentRead()&gt; Repositories\org\apache\poi\poi-ooxml\3.17\poi-ooxml-3.17.jar
&lt;com.microsoft.schemas.office.visio.x2012.main.PagesDocument$Factory: com.microsoft.schemas.office.visio.x2012.main.PagesDocument parse(java.io.InputStream)&gt;
</code></pre>

## Suggested fixing solutions:
Upgrade direct dependency **_org.apache.poi:poi-ooxml-schemas_** from **_3.9_** to **_3.17_**. Because version **_3.17_** includes the above missing methods and is compatible with versions **_3.9_** in the project.
This repair will introduce the following new conflicts, but these conflicts are benign (will not cause runtime exceptions).
Conflict: org.apache.xmlbeans:xmlbeans versions: [2.3.0, /2.6.0]

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] org.ohdsi:rabbit-core:jar:0.10.3
[INFO] +- com.oracle.jdbc:ojdbc14:jar:10.2.0.1.0:compile
[INFO] +- com.microsoft.sqlserver:sqljdbc4:jar:4.0:compile
[INFO] +- mysql:mysql-connector-java:jar:8.0.16:compile
[INFO] |  \- com.google.protobuf:protobuf-java:jar:3.6.1:compile
[INFO] +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  \- xml-apis:xml-apis:jar:1.0.b2:compile
[INFO] +- org.apache.poi:poi:jar:3.17:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  \- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO] +- org.apache.poi:poi-ooxml:jar:3.17:compile
[INFO] |  +- (org.apache.poi:poi:jar:3.17:compile - omitted for duplicate)
[INFO] |  +- <b>(org.apache.poi:poi-ooxml-schemas:jar:3.17:compile - omitted for conflict with 3.9)</b>
[INFO] |  \- com.github.virtuald:curvesapi:jar:1.04:compile
[INFO] +- org.apache.poi:poi-excelant:jar:3.17:compile
[INFO] |  +- (org.apache.poi:poi:jar:3.17:compile - omitted for duplicate)
[INFO] |  +- (org.apache.poi:poi-ooxml:jar:3.17:compile - omitted for duplicate)
[INFO] |  \- org.apache.ant:ant:jar:1.8.2:compile
[INFO] |     \- org.apache.ant:ant-launcher:jar:1.8.2:compile
[INFO] +- <b>org.apache.poi:poi-ooxml-schemas:jar:3.9:compile</b>
[INFO] |  \- (org.apache.xmlbeans:xmlbeans:jar:2.3.0:compile - omitted for duplicate)
[INFO] +- stax:stax-api:jar:1.0.1:compile
[INFO] +- org.apache.xmlbeans:xmlbeans:jar:2.3.0:compile
[INFO] |  \- (stax:stax-api:jar:1.0.1:compile - omitted for duplicate)
[INFO] +- org.postgresql:postgresql:jar:42.2.5:compile
[INFO] +- com.cedarsoftware:json-io:jar:3.0.1:compile
[INFO] +- org.apache.commons:commons-csv:jar:1.1:compile
[INFO] +- commons-lang:commons-lang:jar:2.0:compile
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.hsqldb:hsqldb:jar:2.2.6:compile
[INFO] +- com.healthmarketscience.jackcess:jackcess:jar:2.1.3:compile
[INFO] |  +- (commons-lang:commons-lang:jar:2.6:compile - omitted for conflict with 2.0)
[INFO] |  \- (commons-logging:commons-logging:jar:1.1.3:compile - omitted for conflict with 1.2)
[INFO] +- net.sf.ucanaccess:ucanaccess:jar:3.0.3.1:compile
[INFO] |  +- (org.hsqldb:hsqldb:jar:2.3.1:compile - omitted for conflict with 2.2.6)
[INFO] |  \- (com.healthmarketscience.jackcess:jackcess:jar:2.1.3:compile - omitted for duplicate)
[INFO] +- com.amazon.redshift:redshift-jdbc41:jar:1.1.10.1010:compile
[INFO] +- com.teradata.jdbc:terajdbc4:jar:16.0.0.32:compile
[INFO] +- com.teradata.tdgss:tdgssconfig:jar:16.0.0.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:GoogleBigQueryJDBC:jar:42:compile
[INFO] +- com.simba.googlebigquery.jdbc:google-api-client:jar:1.28.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:google-http-client:jar:1.29.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:gax:jar:1.42.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:google-http-client-jackson2:jar:1.28.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:google-oauth-client:jar:1.28.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:google-auth-library-oauth2-http:jar:0.13.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:google-auth-library-credentials:jar:0.15.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:jackson-core:jar:2.9.6:compile
[INFO] +- com.simba.googlebigquery.jdbc:guava:jar:26.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:google-api-service-bigquery:jar:V2-rev426-1.25.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:opencensus-api:jar:0.18.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:opencensus-contrib-http-util:jar:0.18.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:grpc-context:jar:1.18.0:compile
[INFO] +- com.simba.googlebigquery.jdbc:joda-time:jar:2.10.1:compile
[INFO] +- com.simba.googlebigquery.jdbc:avro:jar:1.8.2:compile
[INFO] \- com.epam:parso:jar:2.0:compile
[INFO]    \- org.slf4j:slf4j-api:jar:1.7.5:compile
</code></pre>

**Comment by MaximMoinat** [comment]
Thanks for reporting and including a solution.

For my information, was this when compiling WhiteRabbit yourself or using the released distribution? If so, what branch/version were you using?

**Comment by Bing-ok** [comment]
I used the latest master branch. This happened when compile and test it myself.

**Comment by Bing-ok** [comment]
Thanks for your support!
