### ISSUE TITLE
mvn install fails with Maven 3.8.1

### ISSUE THREAD

**Issue by don-torok** [OHDSI/WhiteRabbit#298]
Maven 3.8.1 blocks access to unsecured http (not https) sites.  In pom.xml change <url>http://clojars.org/repo/</url> to <url>https://clojars.org/repo/</url> and <url>http://maven.geomajas.org/</url> to <url>https://maven.geomajas.org/</url>

**Comment by MaximMoinat** [comment]
Thanks @don-torok for reporting. Will take this up in a next release.

**Comment by janblom** [comment]
Fixed since v0.10.8
