### ISSUE TITLE
WhiteRabbit_v0.10.4.1->rabbitInAHat.bat does not start on Win10

### ISSUE THREAD

**Issue by rjiang9** [OHDSI/WhiteRabbit#314]
**Describe the bug**
Downloaded whiteRabbit WhiteRabbit_v0.10.4.1 and uncompressed to the same folder as WhiteRabbit_v0.10.3.
When I tried to double click on  rabbitInAHat.bat, the CMD window opens and closed immediately and rabbit-in-a-hat does NOT start. 

But WhiteRabbit_v0.10.3 works just fine.  

**To Reproduce**
1. Go to 'G:\\_OHDSI\WhiteRabbit_v0.10.4.1\bin\'
2. Click on 'rabbitInAHat.bat'

**Expected behavior**
Command line window opens and closes its self right away.
Rabbit-in-a-hat does not start. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro with most recent updates

**Comment by MaximMoinat** [comment]
We have identified the problem; the large number of jar dependencies loaded causes some lines to become too long for Windows to handle. https://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows

We are working on a fix.

**Comment by sebastiaan101** [comment]
I had a similar experience with WR_v010.7 on two Windows 11 computers. Changing the folder didn't work. What did work was 
> on machine 1 and 2: running the .bat file with a  ".\rabbitinahat" command in powershell, instead of "rabbitinahat" - it was advised to use this command 'if you trust the file'. So probably this is related to the windows securtiy issue you mentioned @MaximMoinat. 
> on machine 2 I also had to add the java...\bin folder to the PATH ;-)
