### ISSUE TITLE
WhiteRabit ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

### ISSUE THREAD

**Issue by rjiang9** [OHDSI/WhiteRabbit#317]
**Describe the bug**

When I use WhiteRabbit v0.10.5 to scan and generate the ScanReport.xlsx

ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

All works just fine in v0.10.3. 

[
![1](https://user-images.githubusercontent.com/7293118/140558984-7c3e0bf1-bbe0-4411-a3a9-0fde48867e26.png)
![2](https://user-images.githubusercontent.com/7293118/140558988-0707e08e-4eb7-4382-8a62-569f485f9e99.png)
](url)

**Desktop (please complete the following information):**
 - OS: [win11]
 - Java 8u311

**Comment by MaximMoinat** [comment]
Thanks for reporting. Closing this as duplicate.

The Invalid File Format bug has been described in #316.

The `StatusLogger` error message seems unrelated and can be ignored for now.
