### ISSUE TITLE
Log4j Shell Vulnerability

### ISSUE THREAD

**Issue by saradeelstra** [OHDSI/WhiteRabbit#321]
I’m sure you are well aware of the vulnerability with Log4j.  We are needing to determine if White Rabbit is vulnerable.  If so, do you plan on creating a patch or have a plan to patch?
 
If you could please respond asap, I would greatly appreciate it as we have a deadline of 12/22 to confirm no vulnerabilities, prior to shutting off services to the application.

**Comment by saradeelstra** [comment]
Also inquiring about Usagi software.

**Comment by MaximMoinat** [comment]
Thanks for raising this issue. We are tracking the situation and will follow the solution like being worked on for OHDSI [Atlas/WebApi](https://github.com/OHDSI/WebAPI/pull/1970). We will incorporate this for the next release of WhiteRabbit/Usagi.

At this point, I cannot give you a timeline. As WhiteRabbit/Usagi is typically run locally (ie. not hosted as a webservice), this currently does not have a high priority. If you are uncertain whether this tool may provide a vulnerability, please shut them off until we have implemented the patch.

**Comment by MaximMoinat** [comment]
Further investigation shows that WR does **not** use Log4j, but apache `commons-logging` and `slf4j-simple`. These are not susceptible to the Log4j vulnerability.

@saradeelstra Hope that helps
