### ISSUE TITLE
RedShift driver and code are out of sync

### ISSUE THREAD

**Issue by jeff-m-sullivan** [OHDSI/WhiteRabbit#327]
**Describe the bug**
When attempting to connect to a RedShift database, you get an error:
![Screen Shot 2022-02-01 at 10 54 59 AM](https://user-images.githubusercontent.com/7987295/152002908-6b57e584-6837-49c2-b669-4de9f3766751.png)

This is due to a mistmatch between the version of the driver specified in the pom (42) and the one specified in DBConnector (41). I will submit a PR that addresses this.

**Comment by MaximMoinat** [comment]
Thanks @jeff-m-sullivan for raising this and providing a fix. We will review as soon as possible.

**Comment by MaximMoinat** [comment]
Merged in develop, will be part of a next release.
