### ISSUE TITLE
invalid URL on RabbitInAHat.html page

### ISSUE THREAD

**Issue by wenboown** [OHDSI/WhiteRabbit#333]
**Describe the bug**
on http://ohdsi.github.io/WhiteRabbit/RabbitInAHat.html page:

Loading in a Custom CDM
There are times when users might need to load in a customized version of the CDM, for instance if they are sandboxing new features. To load in a custom CDM schema, first you must create a CSV file that uses the same format as [the existing CDMv5 schema file](https://github.com/OHDSI/WhiteRabbit/blob/master/rabbitinahat/src/main/resources/org/ohdsi/rabbitInAHat/dataModel/CDMV5.csv).

The URL link leads to a 404 page, because `CDMV5.csv` doesn't exist anymore. Maybe change the link to point to the folder instead of a particular file?
https://github.com/OHDSI/WhiteRabbit/tree/master/rabbitinahat/src/main/resources/org/ohdsi/rabbitInAHat/dataModel

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 100.0.4896.75 (Official Build) (x86_64)

**Comment by MaximMoinat** [comment]
Thanks for reporting, should be fixed now
