### ISSUE TITLE
Creating a Stem Table using RabbitInAHat

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/WhiteRabbit#347]
Hi,

I have a question on creating a stem table in Rabbit In A Hat. 

I am following the documentation on [Rabbit In A Hat](http://ohdsi.github.io/WhiteRabbit/RabbitInAHat.html) and was trying to recreate a similar image below as seen in the documentation : 

![image](https://user-images.githubusercontent.com/11243960/184372627-a42e1766-65ee-4877-ba3f-f6606b75ed36.png)

Under the section for stem table, I tried to create a stem table through Edit –> Add stem table. 

- Seem to get one stem table at appears at the top of the RabbitInAHat UI. 

- Tested this with 1 source table (Screenshot provided below): 

![image](https://user-images.githubusercontent.com/11243960/184365065-db2d18f1-2561-4b29-ba78-7cc34bfb5de9.png)

- When I try to click and drag the purple stem_table rectangle nothing seems to happen. 

- Tested this with 2 source tables and still get the same result (Screenshot provided): 

![image](https://user-images.githubusercontent.com/11243960/184370008-9ac93e5e-375d-47c0-9338-05615e9bcd46.png)

Not sure if I'm missing something in the steps that I'm following it from the documentation. 

Many thanks,
Solmaz

**Comment by MaximMoinat** [comment]
Hi @solmazeradat. I am afraid the documentation has a screenshot of an older version of WhiteRabbit. Since v0.10.0, the stem table is shown in the middle instead of on both sides. You can still draw arrows from source to stem and from stem to CDM as before.

The documentation needs updating.
