### ISSUE TITLE
[Suggested Feature] Scroll column panes independent of each other

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#36]
Often times, the source or target tables contain more columns than fit on a single screen. Dragging arrows between columns that aren’t present on the screen together requires a rather tedious, and time consuming click-and-drag action. It would be nice if the source column view and target column view could be scrolled independently of each other. Then the source column and target column could be scrolled next to each other and drawing an arrow becomes much faster.

**Comment by aguynamedryan** [comment]
After assisting @claire-io on #37, it's pretty clear that implementing this feature might be difficult.  Perhaps we implement #15 in the meantime?  If we can independently filter the source columns and the target columns, we can probably fit all the mappings of interest on a single screen.

**Comment by schuemie** [comment]
RiaH now supports filtering, which should alleviate this problem
