### ISSUE TITLE
Update mySQL connector

### ISSUE THREAD

**Issue by elisahenke** [OHDSI/WhiteRabbit#365]
**Describe the bug**
As listed here https://mvnrepository.com/artifact/mysql/mysql-connector-java there is vulnerability in the MySQL Connector Java Version 8.0.25 used within WhiteRabbit. The affected file can be found through the following path: WhiteRabbit_v0.10.7/repo/mysql-connector-java-8.0.25.jar

**Requested change**
This vulnerability should be fixed. Please update the version to v8.0.32.

**Comment by janblom** [comment]
I expect to release a new version of WhiteRabbit in the course of February '23. A review of vulnerabilities in the dependencies will be part of this update.

**Comment by janblom** [comment]
The work and reviews for the next major release of WhiteRabbit take more time than expected. I have prepared a minor update of the current version of WhiteRabbit, which I will merge later today (hoping to get a review first). That will take care of all outdated minor/patch level dependencies and vulnerabilities related to those, including the mysql one.
