### ISSUE TITLE
[Suggested Feature] Select multiple boxes and draw arrows between them

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#38]
Some source formats, e.g. CMS’s LDS, use a denormalized format to store sets of information, e.g. the SynPUF outpatient facility claims file contains up to 45 HCPCS fields. @ericaVoss had to draw 45 separate arrows between the HCPCS fields and the procedure_occurrence.procedure_concept_id. Then she had to draw 45 more arrows between the HCPCS fields and the procedure_occurrence.procedure_source_value.

It would be great to be able to select multiple source columns and multiple target columns and then select something from a drop down menu like “draw arrows” to end up generating arrows between each source column and target column.

This raises some questions about if we should be able to select multiple arrows and apply identical comments/logic text to them, but that’s for another ticket.

**Comment by aguynamedryan** [comment]
We made a little movie showing how this works.  Clicking and dragging individual arrows can be, well, a drag.  Use Shift-Click or CTLR-Click to select multiple tables or fields.  Select multiple source and target tables/fields and use the "Make Mappings" menu option to draw arrows between them all.

![multiarrow](https://cloud.githubusercontent.com/assets/117722/7945861/375ceec4-0928-11e5-95e5-6b141d7f6712.gif)

**Comment by schuemie** [comment]
That's a feature that will save me a lot of time! 

Could I ask you to add this information including the video to the [wiki](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:whiterabbit#connecting_source_fields_to_cdm_fields)?
