### ISSUE TITLE
I can't open the graphical interface of WhiteRabbit and Rabbit-In-a-Hat on Linux (Ubuntu)

### ISSUE THREAD

**Issue by FranSoriano** [OHDSI/WhiteRabbit#397]
**Describe the bug**
I am trying to use WhiteRabbit and Rabbit-In-a-Hat on Linux (Ubuntu) but I can't get the GUI to open. When I double click on the file as indicated in the documentation (https://ohdsi.github.io/WhiteRabbit/WhiteRabbit.html#installation_and_support) it simply opens in a text editor.

**To Reproduce**
1. Use Linux (Ubuntu).
2. Download the latest version of WhiteRabbit from Github.
3. Unzip the download.
4. Double-click on bin/whiteRabbit on Linux to start WhiteRabbit or double-click on bin/rabbitInAHat on Linux to start Rabbit-In-a-Hat depending on the tool you wish to use.

**Expected behavior**
The WhiteRabbit or Rabbit-In-a-Hat graphical interface should open.

**Screenshots**
This is what I get when I double click on bin/whiteRabbit (instead of running the tool, the text editor opens).
![WhiteRabbit](https://github.com/OHDSI/WhiteRabbit/assets/66632994/04f2a701-12ee-4db8-aa7d-c58e0856103d)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Additional context**
I have tried launching WhiteRabbit from the command line and it worked but Rabbit-In-a-Hat is a tool that can only be run through the graphical interface. Your messages and suggestions are important to me because due to this problem I cannot use the tools.

Thank you.

**Comment by janblom** [comment]
Unfortunately the documentation is not entirely correct/complete in this respect. Whether starting the programs through double clicking works, is depending on how your system is configured. There are however some alternatives:

- from the command line, in the directory resulting from unzipping the download, enter the name of the program (script) without any parameters (e.g. bin/whiteRabbit or bin/rabbitInAHat ). This is expected to always work (on Linux/MacOS)
- you might be able to right click on the program you wish to start, and choose an option like "Run as a program"

Hope this helps.
