### ISSUE TITLE
[Suggested Feature] Indicate which CDM columns are required

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#40]
It would be nice to have something simple, like an asterisk, next to any column that is required by the CDM.

**Comment by aguynamedryan** [comment]
I've created a ticket (#45) to discuss how we might store this kind of information.

**Comment by schuemie** [comment]
Note that we currently already have this information in the [csv files](https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/rabbitInAHat/dataModel/CDMv5Model.csv) (see IS_NULLABLE column)

**Comment by aguynamedryan** [comment]
Closed by #57
