### ISSUE TITLE
Oracle instatntclient and matching libocijdbc version on Windows.

### ISSUE THREAD

**Issue by gostrek** [OHDSI/WhiteRabbit#415]
I have a problem with Oracle database connection in White Rabbit on Windows.
The available instatntclient library version, on Oracle website, is 19.23 but White Rabbit release is build against 19.3.

I got: 
Exception in thread "AWT-EventQueue-0" java.lang.Error: Incompatible version of libocijdbc[Jdbc:193000, Jdbc-OCI:1923000...

I have managed to run it on Linux with the link:
https://download.oracle.com/otn_software/linux/instantclient/193000/instantclient-basic-linux.x64-19.3.0.0.0dbru.zip
I've tried to guess:)
https://download.oracle.com/otn_software/nt/instantclient/193000/instantclient-basic-windows.x64-19.3.0.0.0dbru.zip
but without success.

Should I build WhiteRabbit on my own or there is other way I may try?

**Comment by janblom** [comment]
Hi,

thanks for reporting this. I ran the verification suite of WhiteRabbit with ojdbc8 version 19.23.0.0, and that seems fine.

What you could do to test this yourself is to replace the current ojdbc jar in the WhiteRabbit installation (repo\ojdbc8-19.3.0.0.jar) by ojdbc8-19.23.0.0.jar (downloaded from [this location](https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/19.23.0.0/ojdbc8-19.23.0.0.jar)).

If you try this, please let me know the result as I am considering replacing the current ojdbc dependency by the 19.23 one.

Thanks,
Jan

**Comment by gostrek** [comment]
Hi, 
it works. Thank you!

I just put ojdbc8-19.23.0.0.jar along in the repo directory and updated the path:
set PATH=%PATH%C:\Oracle\instantclient_19_23; 
on running (I've added the line in whiteRabbit.bat for convinience).

Regards
Greg

**Comment by janblom** [comment]
Solved with WhiteRabbit version 1.0.0 by switching to the suggested version of Oracle JDBC.
