### ISSUE TITLE
whiterabbit scan report does not include empty tables in the source schema

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/WhiteRabbit#64]
We just ran through an etl design session for the openmrs community.  One issue uncovered was that their source schema included valid tables that we needed to etl, but since that specific instance didn't have any data in some of the tables, they didnt appear in the scanreport.  Can we make it an option to include or exclude empty tables in the report?

**Comment by schuemie** [comment]
This should now be fixed in the [latest release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.5.2).
