### ISSUE TITLE
Remove Ability to Save ETL Spec Using Java-based Serialization

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#73]
We just ran into some issues refactoring the code and had to fix them in #72, we're wondering if using Java's serialization to save ETL spec files is the best approach for saving ETL specs.

At this time, we can't rename the fields in any classes without breaking the ability to read in an ETL spec.  That's a bit of a bummer.

@mav7014 has already implemented an alternative means of serialization using JSON via the [json-io library](https://github.com/jdereg/json-io) which seems a bit more flexible and maleable than Java's native serialization format.  Naively, if we renamed a field in a class, we could, if nothing else, do a find/replace on the serialized JSON and change all the keys in the JSON file to the new field name.  Maybe there are even better ways of allowing us to deserialize an object even if it has been refactored.  But as best as we can tell, native Java serialization makes this hard, if not impossible.

Assuming that we all agree JSON is the better format for serialization going forward we propose the following for milestone 0.5.0:
- Read in ETL specs using either native Java serialization or JSON serialization
- Write out ETL specs **only** in JSON format

In future releases, we'll remove the ability to read in an ETL spec that was saved in native Java format.

This way, users can always use release 0.5.0 to read in their old ETL specs, and then save them back in JSON format in order for those files to be read into any release after 0.5.0.  Essentially, 0.5.0 will serve as a way to convert Java-based files to JSON-based files.  

After 0.5.0 we'll need to come up with a system for reading in older versions of JSON-based ETL specs and migrate them to the latest version of RiaH.

**Comment by schuemie** [comment]
Agreed. Currently, you can already only save in JSON format, and load from both Java serialization and JSON. I'm not very familiar with the JSON to Java library, but if it allows a decoupling of the file format from the Java code we should go for that.

**Comment by aguynamedryan** [comment]
@schumie, well, then I suppose this ticket can be closed, however even though we're moving to a JSON-based format for saving ETL spec files, it seems that the JSON we're saving is very tightly-coupled to the internal structure of the actual code.

As we make changes to the code itself over the next few releases, it's not clear to me how we'll be able to maintain compatibility with older versions of saved ETL specs.

I have little experience creating save files from Java, so based solely on my limited research, it seems like if we want to ensure that we maintain compatibility, we need to create our own custom structure in JSON and develop code that explicitly maps that structure to and from internal classes and their fields.

I'm hoping I'm wrong and someone can correct me.  Should we pop open another issue to continue this discussion elsewhere?
