### ISSUE TITLE
Help Link To Wiki

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WhiteRabbit#87]
I've just started using WhiteRabbit and had an issue connecting to the SQL Server using Windows integrated authentication. I hopped over to the Wiki and found my answer which was to install the SQL Server JDBC drivers. I think it would be helpful to have a "help" icon/link somewhere in the application that would take you to the Wiki and possibly surface that information when using the "Test Connection" button.

**Comment by schuemie** [comment]
I've now added help options to the menu for both WhiteRabbit and RabbitInAHat. This will be included in the next release.
