### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#92]
Some of the graphics we are generating in the [SynPUF ETL Document](https://github.com/OHDSI/ETL-CMS/blob/master/RabbitInAHat/CDMv5_CMS_MDCR_ETL.docx) are too tall to fit on a single page in Word.

Not only that, but I noticed that I'm loosing basic white space between what I enter into a text area in RiaH and what comes out in the Word document.

Lastly, I'd really like to be able to add a bit of light markup to my comments and logic sections so that I have nicely formatted bulleted lists and such in the final document to enhance readability.

I'd love to be able to use [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) (which is what GitHub uses for formatting in issues and wikis) or some other light markup language when I enter text into RiaH.

I imagine we could then weave together all the mappings and graphics into a Markdown document, which can then be translated into many different output formats including HTML, PDF, and yes, Word Docx.

**Comment by markdanese** [comment]
I like this because it would allow for sharing of ETL docs on websites more easily via HTML, and referencing them there.

**Comment by aguynamedryan** [comment]
I've given this feature some more thought and would like to point out some hurdles:

The ETL spec uses tables rather extensively.  Markdown doesn't have support for tables.  There are extensions to Markdown that support tables, but they are rudimentary.  e.g. Markdown tables can't include additional Markdown elements.

To work around this, Markdown allows HTML tags, so we could generate the table in HTML and then insert Markdown statements between ``<td></td>`` tags, but not all interpreters will convert Markdown that is embedded in HTML tags.

Soooooo, we could convert the Markdown in each comment/logic section into HTML, then weave that HTML into a larger HTML document and end up with a cohesive, well-formatted ETL spec in HTML.  But I’m not sure how we’d implement this trick if a user wanted their document as a Word document.

With HTML there are a few problems:

1. HTML isn’t easily editable, meaning users wouldn’t be able to edit their ETL spec after generating it from RiaH
2. HTML isn’t as portable a format as Markdown.  e.g. Converting an HTML document into a Word doc creates a lot of image and formatting issues

Lastly, if we are to introduce Markdown into RiaH, it would be nice to give users some visual feedback about how each logic/comment box will appear once the Markdown is rendered.  We’ll need to have some way of “previewing” the markdown in each box.  I’m thinking maybe a floating window that users can dock next to RiaH that shows them the rendered markdown contents of whatever text box they are currently working on.

With all the issues and complexity raised above, I’m still pretty interested in implementing this feature because I still think allowing Markdown in RiaH best solves the issues/needs I originally described for this ticket. Assuming that RiaH can create a comprehensive enough document, it may be unnecessary for users to edit the ETL specification after it is generated, meaning that read-only HTML is just fine for our target output.

**Comment by schuemie** [comment]
This has been added
