### ISSUE TITLE
CSV RFC 4180 Support

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/WhiteRabbit#93]
I have a few schemas defined in CSV format which comply with [RFC 4180](https://tools.ietf.org/html/rfc4180) but are causing RiaH to bomb out when I try to load them using the new load custom schema option described in #44.

I think we should find a solid Java library for reading in CSV formatted files and use that throughout RiaH and WhiteRabbit.

**Comment by aguynamedryan** [comment]
Anyone have any experience with CSV libraries for Java?

I found [this rather thorough page](http://csveed.org/comparison-matrix.html) on CSV libraries for Java that seems to be about a year old.  Perhaps we should pick a couple from this list to try out for ourselves?

**Comment by schuemie** [comment]
No experience (as you can tell by my home-brew CSV library ;-) ). For no particular reason, why don't we go with the Apache Commons CSV library (the first in the link you sent)? 

Do you want me to take a crack at this? It might be a couple of days before I've got time. The easiest thing would be to change the implementations of `ReadCSVFileWithHeader` and `WriteCSVFileWithHeader`.

**Comment by markdanese** [comment]
If you have time to take a crack, that would be great.  Ryan will have limited time the next few weeks due to "updates" to his family. :)

**Comment by schuemie** [comment]
WIll do!

**Comment by aguynamedryan** [comment]
@schuemie, I think Apache Commons CSV would have been my first choice as well.  Can't wait to see how it works out!

**Comment by schuemie** [comment]
The latest commit (20fbb87fb16b78e31ab5c85f5aebb0a15f3f7f53) introduces the Common CSV library. As far as I can see it works, but can someone else also test it?

**Comment by aguynamedryan** [comment]
@schuemie, my two schemas that were causing errors are working now.  Everything looks good to me.  Thank you very much!
