### ISSUE TITLE
JDBC driver error

### ISSUE THREAD

**Issue by schillil** [OHDSI/WhiteRabbit#96]
Just an FYI, I had to download and install JDBC driver v9.4-1201 from the site below to allow WR/RIaH to connect to my postgres db
https://jdbc.postgresql.org/download.html

**Comment by schuemie** [comment]
I just updated the PostgreSQL drivers in the [latest release](https://github.com/OHDSI/WhiteRabbit/releases/tag/v0.5.2). Hopefully this will solve this problem. If it's not too much trouble, could you test if this works in your environment?

**Comment by schillil** [comment]
Sure will! It's a holiday weekend and I'll be back at work to test on 7/6. Thanks!

**Comment by schillil** [comment]
Tested v5.2 -I get the error "Could not connect: cannot find JDBC driver. Make sure the file postgresql-x.x-xxxx.jdbcx.jar is in the path. Which is the same error I got with 5.0 until I added teh other jdbc driver to the folder.

**Comment by schuemie** [comment]
Hmmm, but 5.2 should contain the new drivers you mentioned. Could you explain a bit more how you managed to fix the old version with the new drivers? Did you just copy them into the WhiteRabbit_lib folder? What were the names of the jar files?

**Comment by schillil** [comment]
OK - I just added these 2 drivers to v5.2 -- copied into WhiteRabbit_lib folder and it works now:
postgresql-9.3-1101.jdbc41
postgresql-9.3-1101.jdbc4
I had also added  the one below (which is what I added to v5.0 and allowed it to work for me, but it didn't allow v5.2 to work for me -so "hmmm" is right)
postgresql-9.4-1201.jdbc41
